### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by engcn** [trzsz/trzsz-ssh#1]
编译试了下太棒了，支持HJKL移动翻页键很方便
- **反馈问题：**
如果ssh长时间无法登陆，使用Ctrl+C也无法退出，如下图:
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/86d4aa91-35b1-468c-971d-e08b39c75a78)
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/519bd02e-089d-45a7-9339-d06b9775782e)

**- 几个建议：**

- 1.tssh后不选择别名，想退出; 建议除了按Ctrl + C可以退出外，增加q键退出;
- 2.由于我的~/.ssh/config中的别名非常多，建议增加类似vim键，gg移到行首，G移到行末;
- 3.切换到搜索模式后，现在只能左手移动到方向键上下移动，建议增加类似fzf搜索工具的方式，对搜索结果可以使用Ctrl + H,J,K,L上下移动，这样左手就不用离开字母区了;

![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/17dce35a-4cfd-4619-be8a-49227c1e9c37)

**Comment by lonnywong** [comment]
> 如果ssh长时间无法登陆，使用Ctrl+C也无法退出

应该加个 timeout 的，我下周末加一下。ctrl + c 无法退出是因为我早早将 stdin 设置为 raw 了，加了 timeout 之后会自己退出的了。

那几个建议我抽空研究下，用的是 https://github.com/manifoldco/promptui ，我看看有没有提供这样的功能。

**Comment by lonnywong** [comment]
@engcn 已解决，可以安装来试试：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@latest
```

**Comment by engcn** [comment]
我很好奇，解决windows下上传慢的问题为什么不在trzsz-go中，而是放在了trzsz-ssh？

**Comment by lonnywong** [comment]
因为 trzsz 依赖 ssh，而慢就慢在 ssh 的输入。我发现所有 Windows 程序的输入都快不了，可能跟 Windows 本身有关。

tssh 的速度快，是因为它直接连远程服务器的，不依赖 Windows 的输入。这只局限于远程服务器是 Linux 的情况。如果远程服务器是 Windows ，那还是慢的，因为这又依赖于 trz 的输入了，又和 Windows 的输入有关。

**Comment by engcn** [comment]
"tssh 的速度快，是因为它直接连远程服务器的，不依赖 Windows 的输入...", 是不是tssh实现了ssh的客户端，不使用windwos自带的ssh客户端？

刚才试了下新版本，提的几个建议都加上了，太棒了。

**Comment by lonnywong** [comment]
> 是不是tssh实现了ssh的客户端，不使用windwos自带的ssh客户端？

对的，用了 go 的 ssh 库 https://pkg.go.dev/golang.org/x/crypto/ssh

**Comment by engcn** [comment]
**使用tssh或者trzsz(v1.1.2)登录后, 在用trz, 报错：**

客户端系统Deepin20.9
服务端系统CentOS Linux release 7.9.2009 

eng@my:~$ tssh tcc
Last failed login: Fri Jun  2 09:06:57 CST 2023 from ****** on ssh:notty
There were 1219 failed login attempts since the last successful login.
Last login: Thu Jun  1 21:11:20 2023 from *******
'abrt-cli status' timed out
[root@VM-0-6-centos ~]# trz -v
trz (trzsz) go 1.1.2
[root@VM-0-6-centos ~]# trz
exec: "zenity": executable file not found in $PATH
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.4/x64/src/runtime/debug/stack.go:24 +0x65
github.com/trzsz/trzsz-go/trzsz.newTrzszError({0xc0000b8050, 0x50}, {0xc00001c4fc, 0x4}, 0x1)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/comm.go:170 +0x272
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvCheck(0xc000051cf8?, {0x591306, 0x3}, 0x28?, 0x17fdc49f71188?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:207 +0x152
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvString(0x46b2a0?, {0x591306?, 0xc000051d18?}, 0x33?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:241 +0x25
github.com/trzsz/trzsz-go/trzsz.(*trzszTransfer).recvAction(0xc0000000c0)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:346 +0x30
github.com/trzsz/trzsz-go/trzsz.recvFiles(0xc0000000c0?, 0xc0000707e0, 0x2b?, 0x3?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/trz.go:52 +0x47
github.com/trzsz/trzsz-go/trzsz.TrzMain()
        /home/runner/work/trzsz-go/trzsz-go/trzsz/trz.go:162 +0x8c5
main.main()
        /home/runner/work/trzsz-go/trzsz-go/cmd/trz/main.go:33 +0x19

[root@VM-0-6-centos ~]#

**Comment by lonnywong** [comment]
客户端安装一下 zenity 这个程序，Linux 原生的。

**Comment by engcn** [comment]
可以了，谢谢

**Comment by engcn** [comment]
选择文件的弹框，可以不依赖于zenity吗？调用系统自带的？

**Comment by lonnywong** [comment]
用的库是依赖这个 zenity 的。直接实现要写的代码、要做的适配太多了，相当于自己实现一些 zenity 的功能。

**Comment by engcn** [comment]
tssh后中无法显示Host通配项呢？

以下是我的部分~/.ssh/config文件内容：
############ ## ###########################
# 代码部署
Host lg-*-deploy
    RemoteCommand /mnt/deploy.sh
Host lg-*-deploy-http
    RemoteCommand curl http://127.0.0.1:9501/deploy

Host lg-t*
    Hostname 192.168.80.11
    User shi

Host lg-uat*
    Hostname 192.168.80.12
    User shi

Host lg-pre-uat*
    Hostname 192.168.80.13
    User shi
############ #############################

使用示例：
# ssh登录用
tssh lg-uat
# 远程部署代码用
tssh lg-uat-deploy
tssh lg-uat-deploy-http

**Comment by lonnywong** [comment]
具体到某个 IP 的，没有必要用通配符了吧？后面有个版本把含有通配符的都过滤了：https://github.com/trzsz/trzsz-ssh/issues/7#issuecomment-1585503999

**Comment by engcn** [comment]
有必要的，看我这种使用场景，多个通配项相互覆盖匹配，
比那个([#7 (comment)](https://github.com/trzsz/trzsz-ssh/issues/1#issuecomment-1585503999))的只有一个通配项的复杂一点，

比如我这么用：
tssh lg-uat-deploy
1.先匹配通配项Host lg-uat*
2.再匹配通配项Host lg-*-deploy

部署项配置(Host lg-*-deploy), 可以匹配3个环境；如果不这么配置，3个环境要再配置3个部署项配置
Host lg-t-deploy
Host lg-uat-deploy
Host lg-pre-uat-deploy

**Comment by lonnywong** [comment]
可以有这些复杂的能配，但包含 HostName 的就不需要通配了？

**Comment by engcn** [comment]
我找到解决方案了，可以这么配置，host后边跟多个别名
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/d8db025c-e5c3-4d35-91b4-cf4b672460a9)
