### ISSUE TITLE
报错，找不到 ssh key

### ISSUE THREAD

**Issue by 80imike** [trzsz/trzsz-ssh#10]
read private key [~/.ssh/dev] failed: open ~/.ssh/dev: no such file or directory

实际上这个文件是存在的，macos 系统 

ssh config 这样配置的

Host dev
    HostName %h
    Port 22
    User root
    IdentityFile  ~/.ssh/dev

**Comment by lonnywong** [comment]
在 `~/.ssh/config` 中，`IdentityFile` 配置要用全路径，它不认识 `~` 的。

如果你是 `tssh -i ~/.ssh/dev` 这样，那是可以的，命令行中是认识 `~` 的，这是 shell 给解释的。

**Comment by 80imike** [comment]
> 

这个可以优化下， ssh  是可以识别 ~/.ssh/dev 的

**Comment by lonnywong** [comment]
OK，我周末优化一下。

**Comment by lonnywong** [comment]
@80imike `IdentityFile` 已支持 `~/`，下一个版本发布前的安装办法：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```
