### ISSUE TITLE
~/.ssh/config 中配置的 SetEnv TERM 无效

### ISSUE THREAD

**Issue by milkpuff** [trzsz/trzsz-ssh#100]
linux环境，终端 kitty 和 foot
最近 tssh 连接后，存在样式不对、行首多一个问号、退格变成空格等问题。修改环境变量 TERM=xterm 可以解决。

但如果仅在 .ssh/config 中设置 `SetEnv TERM=xterm`
此时，本地终端 `echo $TERM`  返回 xterm-kitty (或foot)

1. 使用普通ssh连接，变量 TERM=xterm 成功传递到了服务器，echo $TERM 返回 xterm；
2. 使用tssh连接，变量 TERM=xterm 没有传递到了服务器，echo $TERM 返回  xterm-kitty (或foot)

**Comment by lonnywong** [comment]
看来 openssh 中，配置 `SetEnv TERM=xterm` 的优先级要高于环境变量 `TERM=xterm` 的，我抽空适配一下。

**Comment by lonnywong** [comment]
已解决。

在 `v0.1.20` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
