### ISSUE TITLE
能否支持登录之后切换用户呢？

### ISSUE THREAD

**Issue by bytepoem** [trzsz/trzsz-ssh#101]
比如 ubuntu 用户登录后，`su java` 并输入密码切换为 java 这种。

**Comment by lonnywong** [comment]
你可以用 [自动交互](https://github.com/trzsz/trzsz-ssh/blob/main/README.cn.md#%E8%87%AA%E5%8A%A8%E4%BA%A4%E4%BA%92) 这个功能来实现，也可以用 `RemoteCommand` 来实现，如：

```
Host test
    RemoteCommand sudo su - java
    RequestTTY yes
```
