### ISSUE TITLE
能否做一个忽略的功能呢？ssh中存在很多其实并不需要真的连接的配置。

### ISSUE THREAD

**Issue by t0rjan** [trzsz/trzsz-ssh#102]
<img width="566" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/15151307/9fe52d13-ae45-4e61-b295-3c42975c63a7">

比方说这种东西，不知道我能不能参与一起写写这块代码呢？我觉得这个项目挺有意思的，我可以去看看实现一下这个功能。

**Comment by lonnywong** [comment]
现在，你在 Host 那行最后加个 `*` 开头或结尾，既不影响原来的功能，也不会显示在 tssh 列表中。

不过，感觉也可以再加个配置，如：
`HideHost Yes`

**Comment by t0rjan** [comment]
好的！谢谢！是的，似乎可以增加个配置，我会写golang，但是似乎你这边没有什么开发的相关文档。

**Comment by t0rjan** [comment]
我可以在写好以后，然后提交合并请求

**Comment by lonnywong** [comment]
已支持 `#!! HideHost Yes`。

在 `v0.1.20` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

**Comment by t0rjan** [comment]
nb!
