### ISSUE TITLE
[功能请求] 通过命令行参数传递密码

### ISSUE THREAD

**Issue by GeekDuanLian** [trzsz/trzsz-ssh#104]
`tssh -o'Password xxx' user@host`
似乎无效，程序只会读取配置文件中的内容

希望在配置文件中的条目，都能通过命令行参数来传递，这样可以不用进行配置编辑，简化操作步骤
同时也提供不读取配置文件的功能，避免配置混淆，目前`-F'NUL'`和`-o'UserKnownHostsFile NUL'`均有效，但`~/.ssh/password`不能通过命令行参数指定

**Comment by lonnywong** [comment]
我周末有空了支持一下

**Comment by lonnywong** [comment]
已支持。

在 `v0.1.20` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
