### ISSUE TITLE
可以美化文件传输的进度条吗?

### ISSUE THREAD

**Issue by engcn** [trzsz/trzsz-ssh#106]
今天在[bubbletea](https://github.com/charmbracelet/bubbletea)库的示例中, 看到一个非常漂亮进度条, 如下图.  有没有可能在tssh中美化成这种进度条
![image](https://camo.githubusercontent.com/97e0eb49e313c941097589be47067761984c341876012b1c0aafc16b049dbd32/68747470733a2f2f73747566662e636861726d2e73682f627562626c657465612f627562626c657465612d6578616d706c652e676966)

**Comment by lonnywong** [comment]
你可以试着改改这里：
https://github.com/trzsz/trzsz-go/blob/f55db836285488d0af2d5b4f2542cd47338ee716/trzsz/progress.go#L398

**Comment by engcn** [comment]
我研究研究....

**Comment by sober-wang** [comment]
这个需要图形渲染吧。会过度消耗机器上的资源。

**Comment by kke** [comment]
> This requires graphics rendering, which will consume too much resources on the machine.

No, it's just colored text.

**Comment by lonnywong** [comment]
已支持自定义进度条颜色。

在 `v0.1.22` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

然后在 `~/.tssh.conf`（ Windows 是 `C:\Users\your_name\.tssh.conf` ） 中配置两个颜色，不要带 `#` 号：
```
ProgressColorPair = B14FFF 00FFA3
```

**Comment by pengatgstdev** [comment]
谢谢大佬
