### ISSUE TITLE
按照免密登录配置后，ssh 登录可以免密，但是 tssh 提示请出入密码。

### ISSUE THREAD

**Issue by sober-wang** [trzsz/trzsz-ssh#108]
https://github.com/trzsz/trzsz-ssh/wiki/%E5%85%AC%E9%92%A5%E8%AE%A4%E8%AF%81%E7%99%BB%E5%BD%95

trzsz ssh 0.1.19

**Comment by lonnywong** [comment]
公钥要录入服务器上，如果是堡垒机则要录到堡垒机中。
