### ISSUE TITLE
不论是使用go install还是release版本的tssh都没有内置trz和tsz指令

### ISSUE THREAD

**Issue by jackyzjk** [trzsz/trzsz-ssh#11]
大神你好，我使用tssh登录到远程设备，可压根就找不到trz和tsz的指令，你在README中不是说tssh已内置了trz和tsz么，为何我无法使用，是否是tssh目前还没有集成这两条指令？

**Comment by lonnywong** [comment]
要在服务器上安装 trzsz https://github.com/trzsz/trzsz-go

**Comment by smallevilbeast** [comment]
是本地内置了  不用   trzsz  ssh 了， 服务器需要自己安装

**Comment by jackyzjk** [comment]
明白了，是我理解错了
