### ISSUE TITLE
-R for serveo.net or ssh-j.com on Windows10 and Debian12

### ISSUE THREAD

**Issue by abakum** [trzsz/trzsz-ssh#112]
```
#OpenSSH -R with OpenSSH -J works! 
#`ssh -v rn` or `ssh -v -R test:22:10.161.115.160:22 test@serveo.net`
#`ssh -v rc` or `ssh -v -R test:22:10.161.115.160:22 test@ssh-j.com`
# then
#`ssh -v jn` or `ssh -v -J test@serveo.net root@test`
#`ssh -v jc` or `ssh -v -J test@ssh-j.com root@test`

#OpenSSH -R with tssh -J works too!
#`ssh -v rn` or `ssh -v -R test:22:10.161.115.160:22 test@serveo.net`
#`ssh -v rc` or `ssh -v -R test:22:10.161.115.160:22 test@ssh-j.com`
# then
#`tssh -debug jn` or `tssh -debug -J test@serveo.net root@test`
#`tssh -debug jc` or `tssh -debug -J test@ssh-j.com root@test`

#tssh -R start then exit
#how to fix tssh -R?
#`tssh -debug rn` or `tssh -debug -R test:22:10.161.115.160:22 test@serveo.net`

#tssh -N -R start then hang - BUG?
#`tssh -debug -N rn` or `tssh -debug -N -R test:22:10.161.115.160:22 test@serveo.net`
#tssh -J fail
#`tssh -debug jn` or `tssh -debug -J test@serveo.net root@test`
#OpenSSH -J fail
#`ssh -v jn` or `ssh -v -J test@serveo.net root@test`

#tssh -R start
#`tssh -debug rc` or `tssh -debug -R test:22:10.161.115.160:22 test@ssh-j.com`
#but tssh -J fail
#`tssh -debug jc` or `tssh -debug -J test@ssh-j.com root@test`
#OpenSSH -J fail too
#`ssh -v jc` or `ssh -v -J test@ssh-j.com root@test`
#how to fix tssh -R?
```

<details><summary>#my %HOMEPATH%\.ssh\config</summary>
`

Host target
 User root
 HostName 10.161.115.160
Host rn
 RemoteForward test:22 10.161.115.160:22
 User test
 HostName serveo.net
 PreferredAuthentications keyboard-interactive
Host jn
 ProxyJump test@serveo.net
 User root
 HostName test
Host rc
 RemoteForward test:22 10.161.115.160:22
 User test
 HostName ssh-j.com
 PreferredAuthentications none
Host jc
 ProxyJump test@ssh-j.com
 User root
 HostName test
`
</details>

**Comment by abakum** [comment]
On Debian12
```
debug: login to [rn], addr: serveo.net:22
debug: login to [rn] success
debug: forward listen on remote 'test:22' failed: lookup test on 192.168.0.1:53: no such host
```
On Windows10
```
debug: login to [rn], addr: serveo.net:22
debug: login to [rn] success
debug: forward listen on remote 'test:22' success
``

**Comment by lonnywong** [comment]
Try `ping test` on the remote server.

https://github.com/trzsz/trzsz-ssh/blob/69a174ca2fc663e7cda8adfb73e89f8bae5bc937/tssh/forward.go#L230

**Comment by abakum** [comment]
That's why golang resolved alias on local PC before send request to bind it on remote host?
Well, okay, but why is the debug different, but Windows and Linux?

**Comment by abakum** [comment]
> Try `ping test` on the remote server.
> 
> https://github.com/trzsz/trzsz-ssh/blob/69a174ca2fc663e7cda8adfb73e89f8bae5bc937/tssh/forward.go#L230

Remote hosts serveo.net and ssh-j.com is public jumphost. There is no shell access to them.

**Comment by lonnywong** [comment]
> Well, okay, but why is the debug different, but Windows and Linux?

Are Debian12 and Windows10 local machines? What is the difference in the results of their `ping test` on local ?

**Comment by abakum** [comment]
Debian12 and Windows10 is local machines. test is alias for jumphosts
 I add to /etc/hosts
```
51.15.109.222 tc
138.68.79.95 tn
```
And change ~/.ssh/config
```
#my ~/.ssh/config
Host target
 User root
 HostName 10.161.115.160
Host rn
 RemoteForward tn:22 10.161.115.160:22
 User tn
 HostName serveo.net
 PreferredAuthentications keyboard-interactive
Host jn
 ProxyJump tn@serveo.net
 User root
 HostName tn
Host rc
 RemoteForward tc:22 10.161.115.160:22
 User tc
 HostName ssh-j.com
 PreferredAuthentications none
Host jc
 ProxyJump tc@ssh-j.com
 User root
 HostName tc
```
But the problem remains

**Comment by abakum** [comment]
d

> Try `ping test` on the remote server.
> 
> https://github.com/trzsz/trzsz-ssh/blob/69a174ca2fc663e7cda8adfb73e89f8bae5bc937/tssh/forward.go#L230

On Windows10 `test` is resolved. All ok with debug message

**Comment by abakum** [comment]
> openssh resolves domain names locally, but tssh resolves domain names remotely. Using IP directly should avoid the issue.

#tssh -R start then exit
#how to fix tssh -R?

1koka@debian:~$ tssh -debug rn
debug: /home/koka/.tssh.conf does not exist
debug: open config [/home/koka/.ssh/config] success
debug: decode config [/home/koka/.ssh/config] success
debug: open config [/etc/ssh/ssh_config] success
debug: decode config [/etc/ssh/ssh_config] success
debug: extended config [/home/koka/.ssh/password] does not exist
debug: new ssh agent client [/tmp/ssh-XXXXklzv0D/agent.31174] success
debug: will attempt key: ssh-agent ssh-rsa SHA256:7Q/uIPLtRTP2v7jxnqU5G9FZbEazI2oYv3AEWkWZzHY
debug: add auth method: public key authentication
debug: add auth method: keyboard interactive authentication
debug: add auth method: password authentication
debug: add UserKnownHostsFile: /home/koka/.ssh/known_hosts
debug: UserKnownHostsFile [/home/koka/.ssh/known_hosts2] does not exist
debug: GlobalKnownHostsFile [/etc/ssh/ssh_known_hosts] does not exist
debug: GlobalKnownHostsFile [/etc/ssh/ssh_known_hosts2] does not exist
debug: user declared ciphers: [chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com aes256-gcm@openssh.com aes128-cbc aes192-cbc aes256-cbc]
debug: client supported ciphers: [chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com aes256-gcm@openssh.com aes128-cbc]
debug: login to [rn], addr: serveo.net:22
debug: login to [rn] success
debug: forward listen on remote 'tn:22' success
debug: send env regexp: (^LANG$)|(^LC_.*$)
debug: send env failed: LANG = "ru_RU.UTF-8"
debug: no extended config [ExpectCount] for [rn]
debug: no extended config [EnableTrzsz] for [rn]
debug: no extended config [EnableZmodem] for [rn]
debug: no extended config [EnableDragFile] for [rn]
1koka@debian:~$

**Comment by lonnywong** [comment]
- `tssh --debug`, not `tssh -debug`.
- `tssh -N` usually used with `-f`.

**Comment by abakum** [comment]
[PR](https://github.com/trzsz/trzsz-ssh/pull/111/commits/1142a047194eb99cd279b091f8076a58e721df56) fixed an unexpected exit of `tssh rn` but still not forwarding in contrast with `ssh rn`

**Comment by lonnywong** [comment]
> For ssh-j.com it fix, but for serveo.net the problem still remains.

I don't quite understand the issue. Is there any warning message or error message?

**Comment by abakum** [comment]
case `ssh rn` running
`tssh --debug jn` say:
```
debug: login to [jn] success
debug: no extended config [ExpectCount] for [jn]
...
```
then all ok

case `tssh rn` running
`tssh --debug jn` say:
```
debug: login to [jn], addr: 127.0.0.2:22
proxy [lh@serveo.net] dial tcp [127.0.0.2:22] failed: ssh: rejected: connect failed (Couldn't open remote channel)
```

**Comment by lonnywong** [comment]
> Is there access from China to `serveo.net` and `ssh-j.com`? Would you rather try it yourself?

I'll give it a try when I'm free. What is your current configuration, and which parts do I need to adjust?

**Comment by lonnywong** [comment]
> [PR](https://github.com/trzsz/trzsz-ssh/pull/111/commits/1142a047194eb99cd279b091f8076a58e721df56) fixed an unexpected exit of tssh rn

Have to read the output of `serveo.net` first, then do the remote forward. Otherwise `serveo.net` will close the ssh session.

> but still not forwarding in contrast with ssh rn

Can't [accept](https://github.com/trzsz/trzsz-ssh/blob/b518f228ded7b12d3443374d24922175d2c1bcd5/tssh/forward.go#L365) any connection from `serveo.net` after [listen](https://github.com/trzsz/trzsz-ssh/blob/b518f228ded7b12d3443374d24922175d2c1bcd5/tssh/forward.go#L228). Maybe it's an issue of `golang.org/x/crypto/ssh`.

**Comment by abakum** [comment]
I agree that this is a question for golang, because everything works with a pair of `tssh rc` `tssh jc`!
This is a double question for golang. After all on `serveo.net` running ssh daemon from golang but on `ssh-j.com` dropbear \8^)
