### ISSUE TITLE
无法激活1password的ssh agent

### ISSUE THREAD

**Issue by zhenyuefu** [trzsz/trzsz-ssh#114]
tssh提示输入密码，不会弹出1password窗口
`debug: dial ssh agent ["~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"] failed: dial unix "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock": connect: no such file or directory`

ssh连接正常

ssh config:
```
Include ~/.orbstack/ssh/config

Host *
	IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

Host xxx
	HostName sl.office.fuxi.netease.com
	User xxx
	Port xxx
```

macOS 14.4.1
1Password 8.10.30

**Comment by lonnywong** [comment]
tssh 的配置不支持双引号，你可以去掉双引号试试。

**Comment by zhenyuefu** [comment]
ok去掉引号正常

**Comment by zhenyuefu** [comment]
mac升级14.5之后原生的ssh在没有引号的时候会因为路径中间有空格报错

**Comment by lonnywong** [comment]
可以先建个软链接，避开空格。

**Comment by lonnywong** [comment]
现已支持用引号括起来的空格配置。

在 `v0.1.20` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
