### ISSUE TITLE
类似于xftp实现跨服务器传输文件

### ISSUE THREAD

**Issue by xingchen-FL** [trzsz/trzsz-ssh#118]
有两台服务器，有网络隔离，互相无法访问，在上传文件时，这个可以用tssh实现吗
![xftp拖拽文件上传](https://github.com/trzsz/trzsz-ssh/assets/37186195/1ae22878-ee3b-41cd-8d0d-3dd962745b20)

**Comment by lonnywong** [comment]
先从 A 下载到本地，再从本地上传到 B ？

**Comment by xingchen-FL** [comment]
> 先从 A 下载到本地，再从本地上传到 B ？

是这个逻辑，上传到B后，再把本地文件删掉，能不能用命令一步完成

**Comment by lonnywong** [comment]
没想到太好的办法。可以试试在本机启用 LocalForward 登录 A，本机启用 RemoteForward 登录 B，打通后在 B 直接登录 A，然后用 scp 之类直接复制文件。tssh 暂不支持在没有界面的服务器上选文件。
