### ISSUE TITLE
tssh执行后面直接执行命令报错

### ISSUE THREAD

**Issue by duanjiong** [trzsz/trzsz-ssh#119]
`➜  trzsz-ssh git:(tpz) ✗ ssh 141 bash -c "ls"
usage: tssh [-h] [-v] [-V] [-A] [-a] [-T] [-t] [-g] [-f] [-N] [-p port] [-l login_name] [-i identity_file] [-F configfile] [-J destination] [-o key=value] [-W host:port] [-D [bind_addr:]port] [-L [bind_addr:]port:host:hostport] [-R [bind_addr:]port:host:hostport] [destination [command [argument [argument ...]]]]
error: unknown argument -c
`

**Comment by lonnywong** [comment]
`ssh 141 bash -c "ls"` 中的 `-c` 被解释成参数了，再加个单引号吧，如`ssh 141 'bash -c "ls"'`。

其实还可以直接这样 `ssh 141 ls`

**Comment by duanjiong** [comment]
嗯， 刚才也发现了， 貌似跟标准的ssh语义不一样。
