### ISSUE TITLE
计划支持一种新的传输模式 — 隧道模式，客户端使用 tssh 时生效，服务端先在 Go 版实现。

### ISSUE THREAD

**Issue by lonnywong** [trzsz/trzsz-ssh#12]
基本思路：
1、服务端`trz / tsz` 在启动时，侦听 127.0.0.1 上的一个随机端口，并将端口号告知客户端。
2、`tssh` 作为客户端时，会使用 SSH 隧道尝试与 `trz / tsz` 建立连接，成功则使用隧道模式传输。
3、如果因为跳板机或 `docker exec` 等原因，导致无法与 `trz / tsz` 建立连接，则降级使用 trzsz 原有模式。

场景举例：

| 客户端 | 跳板机 | 服务器 | 传输模式 |
| ----- | ----- | ----- | ----- |
| trzsz ssh | 无 | trz / tsz | 原有模式 | 
| tssh | 无 | trz / tsz | ✅ 隧道模式 | 
| tssh | ssh | trz / tsz | 原有模式 | 
| tssh | tssh | trz / tsz | ✅ 隧道模式 | 
| tssh ( ProxyJump ) | 有 | trz / tsz | ✅ 隧道模式 | 
| tssh ( ProxyCommand ) | 有 | trz / tsz | ✅ 隧道模式 | 
| tssh | 无 | docker exec -> trz / tsz | 原有模式 | 
| tssh | 无 | ssh docker -> trz / tsz | 原有模式 | 
| tssh | 无 | tssh docker -> trz / tsz | ✅ 隧道模式 | 
| trzsz docker exec -> ssh | 无 | trz / tsz | 原有模式 | 
| trzsz docker exec -> tssh | 无 | trz / tsz | 原有模式 | 
| tssh docker -> ssh | 无 | trz / tsz | 原有模式 | 
| tssh docker -> tssh | 无 | trz / tsz | ✅ 隧道模式 |

**Comment by maxid** [comment]
支持端口转发吗？

**Comment by lonnywong** [comment]
> 支持端口转发吗？

会一并支持的

**Comment by lonnywong** [comment]
[tssh v0.1.12](https://github.com/trzsz/trzsz-ssh/releases) 已支持隧道模式。
