### ISSUE TITLE
求教一下为什么我选择列表界面不是箭头而是炸药？

### ISSUE THREAD

**Issue by huaxianyan** [trzsz/trzsz-ssh#120]
![4xdmoaku 12q](https://github.com/trzsz/trzsz-ssh/assets/19589248/bbaeb536-faed-4de5-b915-1f579ba31861)

就像这样，我一开始以为是字体影响了，但是改了别的字体后也是这样

终端是 Windows Terminal，Shell 是 PowerShell，软件版本是 Windows 版（从 Scoop 安装）

虽然不影响使用但是这个问题困扰了我很久，今天还是没忍住来求教

**Comment by lonnywong** [comment]
可以自定义的，https://github.com/trzsz/trzsz-ssh/blob/main/README.cn.md#%E4%B8%AA%E6%80%A7%E9%85%8D%E7%BD%AE

在 `C:\Users\xxx\` 中建一个 `.tssh.conf` 文件，写一行就可以了，你想改成什么都可以，自己试试效果：
```
PromptCursorIcon = >>
```

**Comment by huaxianyan** [comment]
@lonnywong 抱歉文档没看仔细，我看主题里 Tiny 里显示的是这个样子我就试了，但是发现还是改不了

感谢解惑
