### ISSUE TITLE
UDP模式闲置一小段时间就会卡住

### ISSUE THREAD

**Issue by lifei** [trzsz/trzsz-ssh#122]
使用下面👇的命令
```
tssh --reconnect --udp s003
```

闲置一段时间就没有任何响应了。

在server端`kill -9 tsshd`后，客户端将被断开。

**Comment by lonnywong** [comment]
已修复：https://github.com/trzsz/trzsz-ssh/issues/117#issuecomment-2198416424

另外，`--reconnect` 不是用在 `--udp` 的场景下的，是与 `-f` 后台运行一起用的，一般用于端口转发（不登录）的场景。
