### ISSUE TITLE
Windows下无法使用`IdentityAgent`登录

### ISSUE THREAD

**Issue by lifei** [trzsz/trzsz-ssh#123]
ssh_config
```
Host s0* t0* x0*
    IdentityAgent /tmp/.ssh-agent.sock
    #!!IdentityAgent C:\Users\lifei\AppData\Local\Temp\.ssh-agent.sock

```
行为
```
> tssh t001
dial tcp [192.168.196.114:22] failed: dial tcp 192.168.196.114:22: i/o timeout
```

**Comment by lifei** [comment]
Warning: forward to agent [C:\Users\lifei\AppData\Local\Temp\.ssh-agent.sock] failed: open C:\Users\lifei\AppData\Local\Temp\.ssh-agent.sock: The process cannot access the file because it is being used by another process.

**Comment by lonnywong** [comment]
Windows 用 named pipe 的，一般不需要配置 IdentityAgent ，会默认连接 `\\.\pipe\openssh-ssh-agent`，你用的是 openssh 的 ssh agent ，还是其他的？

**Comment by lifei** [comment]
使用的`ssh-pageant`和`pageant`。

**Comment by lifei** [comment]
测了下`ssh-agent`好像是OK的

**Comment by lonnywong** [comment]
putty 的 pageant ？只要打开它，不要配置 IdentityAgent，自动就会连上它，你可以加 --debug 参数确认。

**Comment by lifei** [comment]
![image](https://github.com/trzsz/trzsz-ssh/assets/350000/588576de-a98b-42e2-8d3e-f22fcd15da50)
![image](https://github.com/trzsz/trzsz-ssh/assets/350000/407c66cf-f2bd-4f5a-b23e-4acac12d0ea2)

**Comment by lifei** [comment]
debug: dial ssh agent [C:/Users/lifei/AppData/Local/Temp/ssh-STmq6S4ntPtr/agent.996] failed: The parameter is incorrect.

**Comment by lonnywong** [comment]
优先使用 ssh-agent，要关了它，才会尝试 pageant，不要配置任何 IdentityAgent。

**Comment by lonnywong** [comment]
Windows 一般不需要配置 `IdentityAgent`，如果要配置，也要求配置一个 [Named Pipes](https://learn.microsoft.com/en-us/windows/win32/ipc/named-pipes)，中文叫 [命名管道](https://learn.microsoft.com/zh-cn/windows/win32/ipc/named-pipes)，而不像 Linux 那样是某个文件路径。

- 例如 openssh `ssh-agent` 的命名管道是 `\\.\pipe\openssh-ssh-agent`（ 不配置的话也会默认尝试连接它 ）：
  ```
  Host xxx
      IdentityAgent \\.\pipe\openssh-ssh-agent
  ```

- 对于 putty `pageant`，是没有命名管道的。如果打开了 `pageant`，没有配置 `IdentityAgent`，并且 `ssh-agent` 没有启动，`tssh` 会默认尝试连接 `pageant`。如果要配置 `tssh` 优先使用 `pageant`，可以如下配置（不是很建议，因为这不是一个真实的地址，只是 `tssh` 自定义的一个标识）：
  ```
  Host xxx
      IdentityAgent using_pageant_as_ssh_agent
  ```

**Comment by lonnywong** [comment]
发现 Windows 也是支持 unix socket 的：

https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

https://go-review.googlesource.com/c/sys/+/132555

我在下个版本支持一下，不过要求 ssh agent 自身要正确监听对应的 unix socket 。
