### ISSUE TITLE
通过堡垒机连接后，使用trz上传文件存在问题

### ISSUE THREAD

**Issue by youncyb** [trzsz/trzsz-ssh#124]
## 1. 问题描述
登录方式：tssh user@ip -p2323 --dragfile    // 登录堡垒机
然后到了堡垒机选择机器的界面，选择其中一台后，在命令行界面使用trz -y 上传文件，网速极慢，<=10kb/s
<img width="1287" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/33374470/110f377b-68f9-4114-a0d4-18cdbb01396a">

然后切换到服务器的tmux界面，继续使用tmux -y 上传文件，此时网速能达到100kb/s
<img width="1296" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/33374470/33569e23-850d-401e-82ef-6ffe4343a907">

## 2. 环境
```shell
tssh -V 
trzsz ssh 0.1.21
```

```shell
trzsz -v                                                                                                               
trzsz go 1.1.7
```

## 3. 需求
1. 可以解决因堡垒机导致上传速度慢的问题吗？（我还观察到一个现象，没通过堡垒机登录的机器，命令行界面的上传比tmux中的上传快很多）

**Comment by lonnywong** [comment]
用的是什么堡垒机？这需要堡垒机配合，才能解决的。
有些堡垒机可能会将 `trz` 上传的文件内容，当作是手工的命令输入，在那里做审计，导致速度特别慢。

**Comment by lonnywong** [comment]
1、那个堡垒机支持 `ProxyJump` 不？支持的话，用 `ProxyJump` 直接登录目标机器，可以解决。

2、那个堡垒机能安装 `tssh`，并使用 `tssh` 来登录目标机器不？支持的话，也可以解决。

3、堡垒机是 jumpserver 吗？升级到新版本，好像是没问题的。

其他的话，目前没有太好的办法。

**Comment by youncyb** [comment]
我通过`tssh -J user@堡垒机 root@10.x.x.x`登录后，发现还是和描述中的问题一样。

**Comment by youncyb** [comment]
> 1、那个堡垒机支持 `ProxyJump` 不？支持的话，用 `ProxyJump` 直接登录目标机器，可以解决。
> 
> 2、那个堡垒机能安装 `tssh`，并使用 `tssh` 来登录目标机器不？支持的话，也可以解决。
> 
> 3、堡垒机是 jumpserver 吗？升级到新版本，好像是没问题的。
> 
> 其他的话，目前没有太好的办法。

第2点不行，第3点，没办法确定，我不是公司it部的

**Comment by lonnywong** [comment]
`tssh -J user@堡垒机 root@10.x.x.x` 能登录？中间不应该出现选择机器的，直接就能登录上才是。
如果是这样，那不太符合预期。

测试一下 LocalForward 是否正常？
1、使用 `tssh -J user@堡垒机 -L 9100:127.0.0.1:9101 root@10.x.x.x` 直接登录目标机器。
2、在目标机器上监听 `nc -lNnvp 9101`。
3、在本地机器连接 `nc 127.0.0.1 9100`。
这样，应该要能连上，并且本地输入远程能显示，远程输入本地能显示，才符合预期。

**Comment by youncyb** [comment]
> `tssh -J user@堡垒机 root@10.x.x.x` 能登录？中间不应该出现选择机器的，直接就能登录上才是。 如果是这样，那不太符合预期。
> 
> 测试一下 LocalForward 是否正常？ 1、使用 `tssh -J user@堡垒机 -L 9100:127.0.0.1:9101 root@10.x.x.x` 直接登录目标机器。 2、在目标机器上监听 `nc -lNnvp 9101`。 3、在本地机器连接 `nc 127.0.0.1 9100`。 这样，应该要能连上，并且本地输入远程能显示，远程输入本地能显示，才符合预期。


`tssh -J user@堡垒机 root@10.x.x.x `，直接可以登录到10.x.x.x这台机器上，没有经过堡垒机的机器选择。

**Comment by lonnywong** [comment]
LocalForward 是否正常？

**Comment by youncyb** [comment]
不正常，远端没有接收到
<img width="995" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/33374470/9650a30e-ba83-49c4-90a0-c7d4b7db57d1">

**Comment by lonnywong** [comment]
`tssh --debug -J user@堡垒机 -L 9100:127.0.0.1:9101 root@10.x.x.x` 这样登录，看看有没有报错？
可能是服务器禁止了端口转发。

**Comment by youncyb** [comment]
比较奇怪，我刚刚启用tcp转发，但是显示admin的策略禁用了
<img width="1020" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/33374470/ffe7f30a-ad7c-4862-b1cc-2024738cbc39">
<img width="696" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/33374470/76c0692b-d6bd-4854-8583-6c23de0103e0">

**Comment by lonnywong** [comment]
应该是堡垒机禁用的，这个 ssh 隧道不通，trz 只能走标准输入输出，然后堡垒机在那里审计，导致速度很慢，难搞。

**Comment by youncyb** [comment]
👌🏻，谢谢大佬

**Comment by lonnywong** [comment]
你可以试试 `rz`，tssh 也支持的，有些堡垒机会专门放开 `rz` 的。

**Comment by lonnywong** [comment]
协议不同，之所以改协议，是为了兼容 tmux ，伪装不了。

**Comment by youncyb** [comment]
👌🏻，再次感谢大佬的答疑
