### ISSUE TITLE
tmux批量登录无法分屏

### ISSUE THREAD

**Issue by chenqinru** [trzsz/trzsz-ssh#127]
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/06490b04-1851-412c-8a0e-1b12c62e99ed">

**Comment by lonnywong** [comment]
tmux 是什么版本？

在 tmux 中执行 `tmux splitw -h -t $(tmux display -p '#{pane_id}') -p 50 -P -F '#{pane_id}' tssh` 看看是什么结果？

**Comment by chenqinru** [comment]
> tmux 是什么版本？
> 
> 在 tmux 中执行 看看是什么结果？`tmux splitw -h -t $(tmux display -p '#{pane_id}') -p 50 -P -F '#{pane_id}' tssh`

<img width="780" alt="image" src="https://github.com/user-attachments/assets/31f634ed-86da-43d0-83c6-19229f71c861">
我还要设置啥吗

**Comment by lonnywong** [comment]
感谢反馈。`tmux 3.4` 把 `splitw` 的 `-p` 参数干掉了 https://github.com/tmux/tmux/issues/3836 ，我抽空兼容一下。

**Comment by lonnywong** [comment]
已解决。

在 `v0.1.22` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
