### ISSUE TITLE
windows7系统执行tssh报错“the parameter is incorrect."

### ISSUE THREAD

**Issue by jackyzjk** [trzsz/trzsz-ssh#13]
![tssh_windows7_error](https://github.com/trzsz/trzsz-ssh/assets/15801667/d33a9632-5852-4f33-85ce-2d6262407687)

**Comment by lonnywong** [comment]
指定路径和后缀看看？如 `.\tssh.exe`

**Comment by lonnywong** [comment]
@jackyzjk 你是怎么安装的？安装之后的路径在哪？

**Comment by jackyzjk** [comment]
直接把`tssh.exe`放到E盘，然后开启一个cmd去执行`tssh.exe`就会报错，不论我怎么输入都会报错，即使我以`.\tssh.exe`或者`tssh.exe`执行都是报同样的错误，有点区别就是我现在使用您发布的最新版v0.1.2报错内容变了。
![tssh_windows7_error](https://github.com/trzsz/trzsz-ssh/assets/15801667/c84fd7f8-8530-428e-b056-2085ea166f6d)
还望大神给修复一下。

**Comment by lonnywong** [comment]
@jackyzjk 感谢回复，是下面这个函数报错了：

https://github.com/trzsz/trzsz-ssh/blob/0c85fe0b834e2e03a417a7f28df39e73175ffaa2/term_windows.go#L67C5-L93

设置了三个标记：
| 标记 | Windows 7 是否兼容 |
| ----- | ----- |
| ENABLE_VIRTUAL_TERMINAL_INPUT  | 要安装 KB 2533623 补丁后，才支持 |
| ENABLE_VIRTUAL_TERMINAL_PROCESSING | 支持 |
| DISABLE_NEWLINE_AUTO_RETURN | 不支持，要 Windows 10 才支持 |

你可以在代码中删掉 `DISABLE_NEWLINE_AUTO_RETURN` ，然后自己编译试试？

**Comment by lonnywong** [comment]
@jackyzjk 方便的话，可以加一下 [README.md](https://github.com/trzsz/trzsz-ssh) 最下面留的 QQ 群，一起看看怎么解决这个问题。

**Comment by jackyzjk** [comment]
已加群，排查了一下代码是设置`ENABLE_VIRTUAL_TERMINAL_INPUT`时报的错，即使我安装了`KBKB 2533623补丁`重启电脑执行也还是报错，咨询了一下chatGPT说是此功能要到windows10才支持，但我查了[微软的官方文档](https://learn.microsoft.com/zh-cn/windows/console/setconsolemode)里面提到`最低受支持的客户端是Windows 2000 Professional [仅限桌面应用]`，也就是说window7应该是支持的，搞不定了， 还是得您亲自出手才行

**Comment by lonnywong** [comment]
我安装 Win7 虚拟机研究了，发现 tssh 依赖的很多基础功能都要求 Win10 以上。

在 Win7 建议用其他终端，以下两个终端都支持 trzsz ( trz / tsz ) 上传和下载，不需要安装 tssh 哈：

https://github.com/electerm/electerm

https://tabby.sh/ （ 这个要安装 trzsz 插件 ）

**Comment by lonnywong** [comment]
如果后面改成 [tncon.c](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.c) 和 [tncon.h](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.h) 这两个文件的方式来读取输入，Win 7 再做一些适配，好像也能支持。

跟 Ctrl + Space https://github.com/trzsz/trzsz-ssh/issues/5 的问题变成了同一个依赖了，可能某天可以一并解决。

**Comment by ruanimal** [comment]
> 我安装 Win7 虚拟机研究了，发现 tssh 依赖的很多基础功能都要求 Win10 以上。
> 
> 在 Win7 建议用其他终端，以下两个终端都支持 trzsz ( trz / tsz ) 上传和下载，不需要安装 tssh 哈：
> 
> https://github.com/electerm/electerm
> 
> https://tabby.sh/ （ 这个要安装 trzsz 插件 ）

使用最新0.1.7测试，Win10也不一定好使，至少 ltsb 2015 是不行的。

似乎是对win10的build版本有要求

```

C:\Users\rlj\Desktop\tssh_0.1.7_windows_x86_64>.\tssh.exe
enable virtual terminal failed: 0x57

C:\Users\rlj\Desktop\tssh_0.1.7_windows_x86_64>systeminfo

主机名:           DESKTOP-C84317U
OS 名称:          Microsoft Windows 10 企业版 2015 长期服务方案
OS 版本:          10.0.10240 暂缺 Build 10240
OS 制造商:        Microsoft Corporation
```

**Comment by lonnywong** [comment]
@ruanimal 看来是对 Windows 有最低版本要求，要适配旧版本的 Windows ，就得从 https://github.com/PowerShell/openssh-portable 这里抄，可惜它是用 C 写的，要转成 Go 有较多的工作量。

**Comment by ruanimal** [comment]
在另外一台机器，Windows 10 LTSB 2016 系统，功能正常，确实挺好用的。
也就是当前实现的情况下，版本最低是 Build 14393

```
OS 名称:          Microsoft Windows 10 企业版 2016 长期服务版
OS 版本:          10.0.14393 暂缺 Build 14393
```

**Comment by lonnywong** [comment]
`main` 分支代码支持旧版本 Windows （ 如 Win7 等 ）在 [Cygwin](https://www.cygwin.com/)、[MSYS2](https://www.msys2.org/) 或 [Git Bash](https://www.atlassian.com/git/tutorials/git-bash) 内使用 `tssh` 了。

在下个版本发布之前，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样先安装试用。

**Comment by ruanimal** [comment]
> `main` 分支代码支持旧版本 Windows （ 如 Win7 等 ）在 [Cygwin](https://www.cygwin.com/)、[MSYS2](https://www.msys2.org/) 或 [Git Bash](https://www.atlassian.com/git/tutorials/git-bash) 内使用 `tssh` 了。
> 
> 在下个版本发布之前，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样先安装试用。

这个性能咋样

**Comment by lonnywong** [comment]
> 这个性能咋样

应该没有多少区别。我是装了个虚拟机，简单测试了一下功能，没有长期使用。
