### ISSUE TITLE
[文档问题] 说明文档里描述的rzsz文件传输，怎么使用呢？

### ISSUE THREAD

**Issue by cffycls** [trzsz/trzsz-ssh#130]
*tssh 登录服务器后，内置支持 [trzsz](https://trzsz.github.io/cn/) ( trz / tsz ) 工具，传文件无需另外新开窗口。*

比如本机是windows11，目标机器是Debian12的。使用tssh连接上debian后，发现：
```
# 我在对目标机器也安装tssh后，仍然如此

 ~# sz
-bash: sz: command not found
~# tsz
-bash: tsz: command not found
```
? 是怎么内置、支持的啊

**Comment by lonnywong** [comment]
分服务端和客户端，内置是指客户端内置了。在服务器上要安装 trzsz (  trz / tsz ) 或 lrzsz ( rz / sz )。

**Comment by cffycls** [comment]
说明其实没有内置吧

**Comment by lonnywong** [comment]
看你怎么理解，本来客户端 ssh 是不支持 trzsz 的，tssh 可以看作是 `ssh + trzsz 的客户端`，内置了客户端，没有内置服务端。
