### ISSUE TITLE
用sh脚本的形式，trz上传窗口无法弹出

### ISSUE THREAD

**Issue by liaohongxing** [trzsz/trzsz-ssh#132]
trzsz ssh 0.1.21

trz (trzsz) go 1.1.7

```shell
#!/bin/bash
tssh server1<<EOF
ls -la
trz
EOF
```

比如这段脚本， 出现 ::TRZSZ:TRANSFER:R:1.1.7:2187489899500:42563 就卡着，请问怎么操作能弹出选择文件窗口 。

**Comment by lonnywong** [comment]
为什么要这样做呢？

**Comment by liaohongxing** [comment]
需要将大量手动操作转为自动操作，上面两个命令只是例子 。比如上传一个 go 程序后，后面需要重启systemd , 重启关联服务等等

**Comment by lonnywong** [comment]
但是你要手工选文件这一步，也不是很自动吧。

如果能接受人工选文件，那你可以试试这样用：
```
tssh server1 'ls -la && trz'
```

你用管道的方式，tssh 是不会启用 trzsz 功能的，

**Comment by liaohongxing** [comment]
这个命名试了一下 ，也是无法弹出

**Comment by lonnywong** [comment]
还要加个 `-t` 参数。

**Comment by liaohongxing** [comment]
通过在sh脚本调用 tssh server1 -t "ls -la && trz" 这种形式可以正常工作。暂时解决问题

**Comment by lonnywong** [comment]
现已支持 `--upload-file` 参数在命令行中直接指定上传的文件，详看 https://github.com/trzsz/trzsz-ssh/issues/126#issuecomment-2254511555

**Comment by lonnywong** [comment]
最新的代码已支持 scp 和 sftp，参考 https://github.com/trzsz/trzsz-ssh/issues/199
