### ISSUE TITLE
文档中的 OTP 登陆方式不生效

### ISSUE THREAD

**Issue by wweir** [trzsz/trzsz-ssh#133]
昨天试了一下 TOTP 登陆方式，[此处](https://github.com/trzsz/trzsz-ssh/blob/48da6cc12cdbee9e7451aff2a8cdafb0b1cc4549/README.cn.md?plain=1#L448)文档中记录的方式不生效。

对照着源码看下来，是已经取消了这套实现方式？

1. 麻烦确认下，是否取消了这种登陆方式
2. 如果是遗漏的话，一整套相关的文档可以修复下。或者告知下，我们来 PR
3. [这里](https://github.com/trzsz/trzsz-ssh/blob/48da6cc12cdbee9e7451aff2a8cdafb0b1cc4549/README.cn.md?plain=1#L581) 记录的 OTP 登陆方式是好使的。但相关介绍不够详细，可以再润色一下

**Comment by lonnywong** [comment]
两个适用的场景是不同的。

前者适用于登录成功之后，例如成功登录跳板机之后，要手工选择机器，手工再次输入 otp 的场景。

后者适用于登录成功之前，例如登录跳板机之时要求输入 otp，或者没有跳板机的服务器要求输入 otp。

如果不能明确自己处于哪个阶段，大概率是后者，因为前者是自动交互，一般只有高级用户才会用到。

**Comment by wweir** [comment]
多谢啦！

这种简单的场景举例，给直接加在文档中的话，可以避免很多理解上的困难

**Comment by lonnywong** [comment]
欢迎一起来完善文档，或者编写一些 wiki 指引。

另外还有一个办法，以 `tssh --debug` 运行，看看输出的 debug 信息，看 tssh 在读哪个配置项，你就知道应该配置哪个了。
