### ISSUE TITLE
[jumpserver] ssh config 配置中，用户名带 # 解析失败

### ISSUE THREAD

**Issue by wweir** [trzsz/trzsz-ssh#142]
## jumpserver 给定的登陆方式
<img width="639" alt="image" src="https://github.com/user-attachments/assets/dd37f67e-4b3d-475e-9021-228eaf9cb8b0">
## ssh config 配置
<img width="597" alt="image" src="https://github.com/user-attachments/assets/cf31b098-adcf-493c-b97b-3dca8003fc12">

这个配置 ssh 可以正常解析，tssh 解析时会把用户名中 '#' 后面的部分丢掉

**Comment by lonnywong** [comment]
有 `#` 时，这样配置（ 中间加个 `=` 号 ）：
```
Host xxx
    User = us#er
```

**Comment by wweir** [comment]
> 有 `#` 时，这样配置（ 中间加个 `=` 号 ）：
> 
> ```
> Host xxx
>     User = us#er
> ```

这种奇怪的特例太多，可不是什么好事。特别是还没有足够的 QA 来一一介绍的时候

**Comment by lonnywong** [comment]
> 这种奇怪的特例太多，可不是什么好事。特别是还没有足够的 QA 来一一介绍的时候

我认为 openssh 对于 `#` 是否为注释的处理，太过随意了，没有明确的规则。

**Comment by wweir** [comment]
有点理解 zssh 的实现方式了，直接套个 ssh 子进程去解析这些东西。
曾经也想写个 zssh 的替代的，可惜那段时间没足够精力。
