### ISSUE TITLE
在 Windows Terminal 中使用，资源管理器窗口关闭后，焦点没有回到 Windows Terminal 窗口。

### ISSUE THREAD

**Issue by yanxiangrong** [trzsz/trzsz-ssh#149]
### 环境：
本机：Windows 10，Windows Terminal，Powershell 7
服务器： Ubuntu 24.04，lrzsz

### 问题描述：
在输入 rz 命令后，弹出资源管理器窗口，焦点转移到资源管理器窗口。此时 Windows Terminal 窗口不可用（不能点击和输入）。这是正常的。

上传文件后，资源管理器窗口关闭，焦点没有回到 Windows Terminal 窗口，此时不能输入，这就是问题所在。

用鼠标点击 Windows Terminal 窗口，进入焦点，此时才能输入。

sz 类似。

### 建议：
这个问题导致操作不流畅，望优化。

![image](https://github.com/user-attachments/assets/0505d470-291e-4f62-85c2-c254325e44b6)
![image](https://github.com/user-attachments/assets/feb87e59-41ae-430e-9aa6-cbd680d7057f)

**Comment by fa1seut0pia** [comment]
升级下 Windows Terminal, 版本: 1.21.2701.0 下测试没有问题
Upgrade Windows Terminal, version: 1.21.2701.0 and test without any problems

**Comment by lonnywong** [comment]
Fixed by https://github.com/microsoft/terminal/pull/17828.
