### ISSUE TITLE
不支持~/.ssh/config里Include其他地方的ssh_config吗？

### ISSUE THREAD

**Issue by zenithiks** [trzsz/trzsz-ssh#15]

**Comment by lonnywong** [comment]
用的是 https://pkg.go.dev/github.com/kevinburke/ssh_config 这个库，是支持 Include 的。

我试了一下，发现要放在所有 Host 的前面才行。即先写 Include ，再写其他 Host。
并且，Include 得写绝对路径，不支持 `~/` 的。

**Comment by zenithiks** [comment]
> 用的是 https://pkg.go.dev/github.com/kevinburke/ssh_config 这个库，是支持 Include 的。
> 
> 我试了一下，发现要放在所有 Host 的前面才行。即先写 Include ，再写其他 Host。 并且，Include 得写绝对路径，不支持 `~/` 的。

Include是放在最前面的，但是我这边的Include都是由软件自动插入的，不太好改，比如1password，麻烦大佬研究下能否有办法支持~/的写法

**Comment by lonnywong** [comment]
我研究下

**Comment by molezz** [comment]
同目录便携使用就方便多终端啦。
好像不支持类似vscode中RemoteCommand

```
# Read more about SSH config files: https://linux.die.net/man/5/ssh_config
Host test
    HostName 192.168.1.1
    User test
    RemoteCommand "/bin/fish"
```

**Comment by lonnywong** [comment]
> 好像不支持类似vscode中RemoteCommand

@molezz 支持 RemoteCommand 了的，我自己就一直在用。不过默认是不启用 pseudo-terminal 的，原生 ssh 也这样。
我做成跟原生 ssh 一样的效果了。解决办法是，在 `~/.ssh/config` 中增加下面这样的配置：
```
Host *
    RequestTTY  Yes
```

**Comment by molezz** [comment]
> > 好像不支持类似vscode中RemoteCommand
> 
> @molezz 支持 RemoteCommand 了的，我自己就一直在用。不过默认是不启用 pseudo-terminal 的，原生 ssh 也这样。 我做成跟原生 ssh 一样的效果了。解决办法是，在 `~/.ssh/config` 中增加下面这样的配置：
> 
> ```
> Host *
>     RequestTTY  Yes
> ```

3x，好用， 只要第一行启用就好
```
RequestTTY  Yes
Host a
    HostName a
    Port 22
    User a 
    RemoteCommand "/bin/fish"

Host b
    HostName b
    Port 22
    User b
    RemoteCommand "/bin/fish"
```

**Comment by lonnywong** [comment]
@zenithiks 已支持 `Include ~/other/config`，可以这样安装试试：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```

**Comment by lonnywong** [comment]
v0.1.3 已支持
