### ISSUE TITLE
tssh 对 luit 支持度不好

### ISSUE THREAD

**Issue by kaixinmeepo** [trzsz/trzsz-ssh#152]
远端linux系统是gbk，这个没办法改。尝试使用luit，会出现直接跳过输入私钥的密码，而报错。
命令是  luit -encoding gbk tssh XXXX
报错：
$ luit -encoding gbk tssh XXXX
Warning: could not change permissions of tty -- pty is insecure!
Enter passphrase for key '~\.ssh\id_rsa':
new conn [XXXXXXX:XXX] failed: ssh: handshake failed: The handle is invalid.

**Comment by kaixinmeepo** [comment]
使用config把密码配置上倒是能绕开上边的问题。但是发现另一个问题：登录上去后发现还是乱码，用ssh是正常的

**Comment by lonnywong** [comment]
你可以试试设置 LANG 等环境变量。

**Comment by kaixinmeepo** [comment]
> 你可以试试设置 LANG 等环境变量。
调整过LANG和LC_ALL，但是没有用。

**Comment by kaixinmeepo** [comment]
登录乱码的原因找到了：应该是我是用的git bash环境下的luit，所以执行luit需要它的环境，在terminal中使用 "C:\\Program Files\\Git\\bin\\bash.exe --login -i -c \"luit -encoding gbk tssh XXX\"" 就可以了，但又有新的问题：
使用 ctrl + c 终止命令同时会把整个shell窗口关掉。当然如果上边命令使用ssh就没有这个问题。
另外我想问下有没有 tssh XXX 连接某个远程机时 同时在远端执行一段命令“luit --encoding gbk”呢

**Comment by lonnywong** [comment]
你可以试试这样配置：
```
Host xxx
    RequestTTY yes
    RemoteCommand luit -encoding gbk bash --login
```

**Comment by kaixinmeepo** [comment]
> 你可以试试这样配置：
> 
> ```
> Host xxx
>     RequestTTY yes
>     RemoteCommand luit -encoding gbk bash --login
> ```

上述方法不太行，本来正常登录的编码是zh_CN.GBK，现在变成了这样：
XXXXXXXXXX:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
有可能luit还需要bash登录环境才可以。命令改成如下是可以使用的：
`RemoteCommand bash --login -c "luit -encoding gbk"`
