### ISSUE TITLE
是否支持 .ssh/config 自定义private key

### ISSUE THREAD

**Issue by SidneyCao** [trzsz/trzsz-ssh#16]
是否支持 .ssh/config 自定义private key

例如
Host x.x.x.x
        User ubuntu
        IdentityFile ~/.ssh/id_ed25519

**Comment by lonnywong** [comment]
已经支持了的 https://github.com/trzsz/trzsz-ssh/issues/3

现在是有遇到什么错误或问题不？

**Comment by boomker** [comment]
<img width="1440" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/6276d73c-c9a9-41af-b35e-af796a3a7e47">

大佬,  ssh 可以连接, 但是使用 go 版的 tssh 反而不能连接了

**Comment by boomker** [comment]
<img width="1440" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/b22aab9c-8ddd-4451-8785-44a31f0b3451">

大佬, 我这边使用的是最新的 Go 版的 tssh, 发现 ssh 可以连接远程机器,tssh 反而不行

**Comment by boomker** [comment]
解决了, 我删除了 ~/.ssh/known_hosts中对应的条目指纹数据, 重新连接就好了
