### ISSUE TITLE
tssh 使用 mac 上 OrbStack 生成的 ProxyCommand 不正常

### ISSUE THREAD

**Issue by bigruid** [trzsz/trzsz-ssh#160]
使用ssh可以正常登录，tssh登录报错

![image](https://github.com/user-attachments/assets/ffe013da-1f7a-47ca-8921-31770b12ef64)

![image](https://github.com/user-attachments/assets/26827df8-6210-424e-bb03-71111713dd94)

**Comment by lonnywong** [comment]
如果手工执行那个 ProxyCommand 会是什么结果？

**Comment by bigruid** [comment]
手工执行会报其他错，不太了解它是怎么实现的
![image](https://github.com/user-attachments/assets/5c9948a5-2474-44de-8d5e-0ec0cb5448f0)

**Comment by lonnywong** [comment]
你这样执行看看？
```
cat | '/App...' ssh... 501
```

**Comment by bigruid** [comment]
执行之后会卡在红线位置，再按一下回车会输出红线下面的内容
![image](https://github.com/user-attachments/assets/40aeeab4-fa99-4b4e-bcdf-90637d86056b)

**Comment by lonnywong** [comment]
我知道了，你的配置中有 `ProxyUseFdpass`，这是 tssh 现在不支持的。

```
ProxyUseFdpass
        Specifies that ProxyCommand will pass a connected file descriptor back to ssh(1) instead of continuing to execute and pass data.  The default is no.
```

**Comment by bigruid** [comment]
OK

**Comment by lonnywong** [comment]
你看看 OrbStack 有没有不带 fdpass 的用法？

**Comment by bigruid** [comment]
翻了下 orbstack 的 issuss，发现去掉 ProxyCommand 配置也能用，我直接注释掉了
https://github.com/orbstack/orbstack/issues/436#issuecomment-1630802050
