### ISSUE TITLE
支持多线程文件传输

### ISSUE THREAD

**Issue by ghost** [trzsz/trzsz-ssh#162]
如果能支持多线程文件传输就更好了，彻底告别winscp

**Comment by lonnywong** [comment]
你说的多线程是指代码层面的？现在是用 go 实现的，会自动创建适当的线程。

如果不是指代码层面的线程，不是很明白具体是个什么样的需求。是指后台传输？是支持的，加个 `-f` 参数，如`trz -f` 即可。

**Comment by lonnywong** [comment]
多个连接不太好实现。另外，多个连接不一定比单个连接快很多吧，理论上不都是到带宽上限？

**Comment by lonnywong** [comment]
udp 模式也支持传文件的
