### ISSUE TITLE
decode config failed: ssh_config: Match directive parsing is unsupported

### ISSUE THREAD

**Issue by u3u** [trzsz/trzsz-ssh#18]
我同时使用 [Fig](https://fig.io) 终端自动完成，它也会列出 `~/.ssh/config` 列表，并且会往文件末尾写入 `Match` 指令，`tssh` 无法解析它

https://fig.io/user-manual/servers
https://fig.io/user-manual/autocomplete/ssh

```sh
# Fig ssh integration. Keep at the bottom of this file.
Match all
  Include ~/.fig/ssh
```

另外我还有一个疑问，是不是用 `tssh` 的话就可以在任意终端直接使用（比如 VSCode 内置终端）而不需要像 [iTerm2](https://trzsz.github.io/cn/iterm2) 那样手动配置了？因为我更喜欢文本进度条，但现在 iTerm2 最新版还是 `3.4.19`，不想折腾升级 `nightly` 版本

**Comment by lonnywong** [comment]
@u3u 你配置的 host 主要是在 Match 的前面的吧，让 tssh 忽略 Match 的内容应该也可以？

> 另外我还有一个疑问，是不是用 tssh 的话就可以在任意终端直接使用（比如 VSCode 内置终端）而不需要像 [iTerm2](https://trzsz.github.io/cn/iterm2) 那样手动配置了？因为我更喜欢文本进度条，但现在 iTerm2 最新版还是 3.4.19，不想折腾升级 nightly 版本

是的，只要用 tssh 登录，在服务器上安装 trzsz 就可以了，客户端不用再安装或配置其他什么了。

**Comment by u3u** [comment]
> 你配置的 host 主要是在 Match 的前面的吧，让 tssh 忽略 Match 的内容应该也可以？

是的，Match 这个是在文件最末尾的，读取配置时忽略掉就可以了

> 是的，只要用 tssh 登录，在服务器上安装 trzsz 就可以了，客户端不用再安装或配置其他什么了。

感谢，那太方便了 👍

**Comment by lonnywong** [comment]
@u3u 已忽略 Match ，可以这样安装试试：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```

**Comment by u3u** [comment]
谢谢！现在可以列出 Host 列表了 👍

但在连接时出现了另一个错误：

```
new knownhosts [~/.ssh/known_hosts] failed: knownhosts: ~/.ssh/known_hosts:7: illegal base64 data at input byte 3
```

对了，现在 `IdentityFile ~/.ssh/id_rsa` 这个也是支持的吧，我看 issues 里有人提过了

**Comment by lonnywong** [comment]
> new knownhosts [~/.ssh/known_hosts] failed: knownhosts: ~/.ssh/known_hosts:7: illegal base64 data at input byte 3

`~/.ssh/known_hosts` 第 7 行与 go 的 https://pkg.go.dev/golang.org/x/crypto/ssh/knownhosts 不兼容，把第 7 行删了，应该就可以了。

> 对了，现在 IdentityFile ~/.ssh/id_rsa 这个也是支持的吧，我看 issues 里有人提过了

支持了的。

**Comment by u3u** [comment]
好的，我用 VSCode 打开之后发现了，之前这行注释符号是 `; ` 我改成 `# ` 注释就可以了
感谢这个伟大的项目！我测试没有什么问题了，体验非常棒 👍
