### ISSUE TITLE
Ctrl + Alt + ] 快捷键没有效果

### ISSUE THREAD

**Issue by ponyjoy** [trzsz/trzsz-ssh#19]
非常感谢，工具非常好用。

Ctrl + Alt + ] 快捷键
没有效果，无法退出终端
这是不是一个通用的快捷键

**Comment by lonnywong** [comment]
你用的是什么终端？这快捷键应该是终端的。

**Comment by ponyjoy** [comment]
哈，确实是，我用的windows terminal。似乎这没有这个快捷键了

**Comment by lonnywong** [comment]
Windows Terminal 默认关闭当前 pane 的快捷键是：Control + Shift + W

 也可以进行自定义配置的，你可以网上去找找看，或者问问 ChatGPT 。

**Comment by ponyjoy** [comment]
> Windows Terminal 默认关闭当前 pane 的快捷键是：Control + Shift + W
> 
> 也可以进行自定义配置的，你可以网上去找找看，或者问问 ChatGPT 。

我主要是用于退出登录,可以使用<kbd>Ctrl + D</kbd>
