### ISSUE TITLE
tssh连接远程终端后，方向键不可用

### ISSUE THREAD

**Issue by CruiseTian** [trzsz/trzsz-ssh#2]
使用tssh连接上远程终端后，无法使用方向上下键选择之前的命令
Windows terminal 1.16.10261.0
go version: 1.20.4

**Comment by lonnywong** [comment]
好像 win 下有些键是有问题，我周末研究看看。

**Comment by lonnywong** [comment]
@CruiseTian 已解决，可以安装来试试：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@latest
```
