### ISSUE TITLE
prompt选择乱码

### ISSUE THREAD

**Issue by yangmingsen** [trzsz/trzsz-ssh#21]
![image](https://github.com/trzsz/trzsz-ssh/assets/30111026/f320f2fb-0c13-4dfc-9661-9733b79345ce)
这两个字符在我的win10和centos7中无法显示，我表示很伤心.
![Image_20230620152412](https://github.com/trzsz/trzsz-ssh/assets/30111026/635864ab-8299-485a-8ca3-94a3b8a4aec5)

**Comment by lonnywong** [comment]
应该换个字体就可以了

**Comment by yangmingsen** [comment]
> 应该换个字体就可以了

我准备换成 “>” 简单通用
