### ISSUE TITLE
虚拟机win7报错 0x57

### ISSUE THREAD

**Issue by yangmingsen** [trzsz/trzsz-ssh#22]
![1687322892218](https://github.com/trzsz/trzsz-ssh/assets/30111026/4dec5998-0ef1-46ac-b5b4-3d6dbeb42b57)
这个是不支持虚拟机吗？

**Comment by lonnywong** [comment]
支持虚拟机，不过现在还不支持 Win7 https://github.com/trzsz/trzsz-ssh/issues/13

**Comment by lonnywong** [comment]
`main` 分支代码支持在 [Cygwin](https://www.cygwin.com/)、[MSYS2](https://www.msys2.org/) 或 [Git Bash](https://www.atlassian.com/git/tutorials/git-bash) 内使用 `tssh` 了。

在下个版本发布之前，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样先安装试用。
