### ISSUE TITLE
Bad owner or permissions on...问题

### ISSUE THREAD

**Issue by yangmingsen** [trzsz/trzsz-ssh#23]
我在本地 .ssh目录下创建 config文件后，可以使用 tssh，但我再使用ssh命令就用不了了，报 Bad owner or permissions on...。
![image](https://github.com/trzsz/trzsz-ssh/assets/30111026/eb6072f3-870d-4d51-a03d-9959e95349c5)
![image](https://github.com/trzsz/trzsz-ssh/assets/30111026/df37bd86-7df8-49c8-9443-defafd80bee4)
这个问题好像是ssh继承权限问题，我用的是windows10自带的openSSH
![image](https://github.com/trzsz/trzsz-ssh/assets/30111026/3d823f40-a84d-455a-beca-5f090a703c72)
解决方案是换个ssh，比如安装Git时带的ssh就行。 

在linux上也是，比如centos7
![1687412660873](https://github.com/trzsz/trzsz-ssh/assets/30111026/0c770707-e6db-4481-a675-9d7c1c60a7f5)

你们是怎么解决这个问题的？

**Comment by lonnywong** [comment]
ssh 会强校验 `~/.ssh/config` 等文件的权限，在 Linux 一般只要执行 `chmod 700 ~/.ssh && chmod 600 ~/.ssh/*` 就好了。

在 Windows 也是要设置好这些文件的权限，可以网上搜一些教程，如：https://www.virtualizationhowto.com/2022/02/bad-owner-or-permissions-on-ssh-config-windows-10/

**Comment by lonnywong** [comment]
参考 https://windowsreport.com/bad-owner-or-permissions-on-ssh-config/ 这个设置即可
