### ISSUE TITLE
can't get public key from '/Users/xxx/.ssh/id_rsa'

### ISSUE THREAD

**Issue by la-cat** [trzsz/trzsz-ssh#25]
版本：github releases 下载0.1.4二进制文件（tssh_0.1.4_macos_aarch64.tar.gz）
系统：m1 pro
不管去掉IdentityFile 参数，还是加上或者换上绝对路径就是提示获取不到，也试过tssh -i path 也是一样。
![tssh-1](https://github.com/trzsz/trzsz-ssh/assets/37959871/861b122e-a19c-43d6-a13b-7207f9bb56b4)
![tssh-2](https://github.com/trzsz/trzsz-ssh/assets/37959871/18e43e83-731a-44bc-a969-067a5add9d1a)

**Comment by la-cat** [comment]
额…… 我重新用ssh-keygen 生成了一个可以用了，前面那个密钥是用xshell 生成的，不知道是不是和这个有关系。
xshell 生成的：-----BEGIN RSA PRIVATE KEY-----
ssh-keygen 生成的：-----BEGIN OPENSSH PRIVATE KEY-----

**Comment by lonnywong** [comment]
你这个私钥是有密码保护的吧？
tssh 跟服务器握手时，需要先提供公钥，确认服务器支持该公钥登录，然后才要求用户输入密码。
openssh 生成的公私钥对，有密码保护时，也能从私钥文件中读取到公钥的（ go 的 ssh 库内置支持了 ）。
非 openssh 生成的公私钥对，等我有空了，研究一下怎么搞。可能是有一个对应的公钥文件可以读取？

**Comment by la-cat** [comment]
xshell 生成的key有密码的。我也重新试了一下openssh 生成+密码，和你说的一样，会提示验证密码，验证完后能正常登陆，应该还是和非openssh 生成的密钥有关系。

另外工具超赞的 ^_^

**Comment by lonnywong** [comment]
有密码的，现在是只支持 openssh 生成的。
后面有空再研究一下非 openssh 的怎么搞，不过优先级可能不高，因为 openssh 可以生成各种类型的密钥对。

**Comment by lonnywong** [comment]
@la-cat 只要在私钥旁边有个公钥文件 `*.pub` ，就可以支持 `-----BEGIN RSA PRIVATE KEY-----` 这种了。
在  `v0.1.6` 发布前，可以从最新源代码安装试用：`go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`
