### ISSUE TITLE
Ubuntu下vim打开文件显示一半，退出vim后无法在输入

### ISSUE THREAD

**Issue by smallevilbeast** [trzsz/trzsz-ssh#26]
如题

**Comment by smallevilbeast** [comment]
用的是最新版

**Comment by smallevilbeast** [comment]
链接到ubuntu server 20.04

**Comment by smallevilbeast** [comment]
打开的文件要超过一屏

**Comment by smallevilbeast** [comment]
客户端是 ubuntu 23.04

**Comment by lonnywong** [comment]
退出 vim 时，vim 处于什么模式？是 insert mode 还是 normal mode ？是怎么退出的？

用 openssh 会不会有同样的问题？

**Comment by smallevilbeast** [comment]
我知道怎么重现了   正常窗口打开 通过tssh进入服务器   然后再把终端窗口全屏    再vim 或其他操作  都是显示一半

感觉是终端窗口大小变化  没有监听

**Comment by lonnywong** [comment]
有处理窗口大小的事件的：
https://github.com/trzsz/trzsz-ssh/blob/030c0613ccdb9a3a3b085b43a1969540f9b78972/term_unix.go#L68-L79

可能是某个原因导致不生效，用的是 https://github.com/creack/pty 这个组件，用它首页的示例看看有没有问题？

**Comment by lonnywong** [comment]
我知道问题了，周末修一下。

**Comment by lonnywong** [comment]
@smallevilbeast 应该修复了，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样安装验证下。

**Comment by smallevilbeast** [comment]
是可以了， 这下完美了
