### ISSUE TITLE
是不是还缺一个共享session能力

### ISSUE THREAD

**Issue by Nuclear6** [trzsz/trzsz-ssh#29]
Host *
    ControlMaster auto
    ControlPath ~/.ssh/master-%r@%h:%p

**Comment by lonnywong** [comment]
现在是还不支持的，等 go ssh 库支持后，再研究一下怎么实现。https://github.com/golang/go/issues/32958

**Comment by lonnywong** [comment]
已支持 ControlMaster、ControlPath 和 ControlPersist。在 v0.1.13 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装后的路径在 ~/go/bin/tssh 。

**Comment by Nuclear6** [comment]
Warning: start control master failed: stdout read failed: EOF
Warning: dial ctrl unix
不知道咋配置 ，一直报warning

**Comment by lonnywong** [comment]
加上 --debug 运行，看看输出什么？

**Comment by lonnywong** [comment]
@Nuclear6 另外，你的远程服务器是什么操作系统的？

**Comment by Nuclear6** [comment]
debug感觉也没啥有用信息，如果我在config文件填写ControlMaster auto，执行tssh xxxx现状是：会先提示我输入答案，我不输入，一直回车，就会到这个warning，不管她继续回车就到了加载答案开始我的手机认证流程
服务器是centos6

**Comment by Nuclear6** [comment]
我大概明白你意思了，我这边不太好用

**Comment by Nuclear6** [comment]
现在只要配置ControlMaster就提示那个warning，我把答案给去掉了也不太行，不知道还有没有其他版本要求

**Comment by lonnywong** [comment]
你可以在命令行指定不要 ControlMaster，如 `tssh -oControlMaster=no xxx`

**Comment by Nuclear6** [comment]
那跟我不配置ControlMaster auto是不是一样效果

**Comment by lonnywong** [comment]
是的，如果你觉得“记住密码”比 ControlMaster 好用，你可以那样配置，也可以把 auto 改为 no （不配置的默认值也是 no）

**Comment by lonnywong** [comment]
计划用类似 `expect` 的方式，支持开启了 `ControlMaster` 时的记住密码功能：https://github.com/trzsz/trzsz-ssh/issues/64#issuecomment-1853170951
