### ISSUE TITLE
考虑下支持 config 中的`IdentityFile`

### ISSUE THREAD

**Issue by tille1229** [trzsz/trzsz-ssh#3]
```
Host test
	HostName www.baidu.com
	port 22
	user root
	IdentityFile ~/.ssh/baidu/id_rsa
	PubkeyAcceptedKeyTypes +ssh-rsa
	HostKeyAlgorithms +ssh-rsa
```
例如一个配置文件中的定义，路径可能不在` .ssh`目录下。

**Comment by lonnywong** [comment]
@engcn 因为有通配的存在，显示所有参数项不太好搞，可以加一些通用的、关键的，如 IdentityFile ，当值不为空时，就显示出来。
我感觉下面这些会比较关键些，不知还有没有其他的：
```
HostName
Port
User
IdentityFile
ProxyJump
ProxyCommand
```

**Comment by engcn** [comment]
> 通用的、关键
也可以呀，我常用还有这几项，
RemoteCommand
DynamicForward
LocalForward
RemoteForward

**Comment by lonnywong** [comment]
@engcn 你这是要把 ssh 的功能全搬过来呀 😂

**Comment by engcn** [comment]
哈哈，我那几项，可能别人不常用，不加也行，随意吧

**Comment by engcn** [comment]
谢谢大神

**Comment by lonnywong** [comment]
[v0.1.1](https://github.com/trzsz/trzsz-ssh/releases/tag/v0.1.1) 除了转发，其他基本功能都实现了，包括：
```
IdentityFile
ProxyJump
ProxyCommand
RemoteCommand
ServerAliveInterval
ServerAliveCountMax
```

**Comment by lonnywong** [comment]
@engcn 发现 `RemoteCommand` 忘记读配置了，已修复。因为还没有打新的 tag ，需要这样安装：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@e5fd842
```

**Comment by engcn** [comment]
OK

**Comment by hsh7654321** [comment]
@lonnywong 感谢抽空实现。现在有个问题请教下，会提示 `read private key [~/.ssh/private/id_rsa] failed: open ~/.ssh/private/id_rsa: The system cannot find the path specified`。是不是`~`无法识别。能不能在解析路径之前将`~`映射到`home`目录，同时考虑下 window 中 `/`路径的问题。因为会在一些类bash中使用。谢谢！

**Comment by lonnywong** [comment]
@hsh7654321 `~/` 我会替换成 `HOME` 目录，预计周末实现，https://github.com/trzsz/trzsz-ssh/issues/10

关于 Windows 中 `/` 路径的问题，你是怎么配置的，怎么使用的，然后出了什么错误？

**Comment by hsh7654321** [comment]
@lonnywong 我试了下，`Windows` 中使用`bash`客户端 用`/` 代替路径中`\`的，所以可以忽略。

**Comment by lonnywong** [comment]
@hsh7654321  `IdentityFile` 已支持 `~/`，下一个版本发布前的安装办法：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```

**Comment by lonnywong** [comment]
@engcn [v0.1.4](https://github.com/trzsz/trzsz-ssh/releases/tag/v0.1.4) 已支持 ssh 端口转发，包括以下配置项：
```
DynamicForward
LocalForward
RemoteForward
```
