### ISSUE TITLE
choco支持

### ISSUE THREAD

**Issue by dengbojing** [trzsz/trzsz-ssh#31]
windows是否考虑一下支持choco方式安装

**Comment by lonnywong** [comment]
我抽空研究下

**Comment by lonnywong** [comment]
@dengbojing 提交上去一周多，还没人审核：https://community.chocolatey.org/packages/tssh

建议使用 https://scoop.sh/ ，这个不用等那么久。

**Comment by dengbojing** [comment]
我已经用上了，直接下载执行文件，配置环境变量，感谢你的工具，非常好用，非常感谢

**Comment by dengbojing** [comment]
choco package repository 里面看到了 0.1.7版本, 这下更方便管理了
