### ISSUE TITLE
prompt 显示的host列表能否包含 ~/.ssh/config 文件Include里的host

### ISSUE THREAD

**Issue by hzhq1255** [trzsz/trzsz-ssh#35]
`~/.ssh/config`
Include ~/.ssh/test_config

Host node1
  User root

`~/.ssh/test_config`
Host node2
  User root

但是现在的最新版本不会显示node2，只会显示node1，我自己fork了一版改了下，但是属性好像都没暴露用反射搞了挺麻烦的😂。

![image](https://github.com/trzsz/trzsz-ssh/assets/55423612/ff547fd1-a368-408d-8d17-cf30e063e729)

**Comment by lonnywong** [comment]
可以先改 https://github.com/trzsz/ssh_config 这个，然后再改 trzsz-ssh 。

这是个问题，我还在忙着其他的，你有空可以先研究看看。

**Comment by hzhq1255** [comment]
> 可以先改 https://github.com/trzsz/ssh_config 这个，可以提个 PR 到 https://github.com/trzsz/ssh_config 的 main 分支。
> 
> 这是个问题，我还在忙着其他的，你有空可以先研究看看。
我提 PR 了  有时间看下👀 https://github.com/trzsz/ssh_config/pull/1

**Comment by lonnywong** [comment]
然后 trzsz-ssh 也提个 PR ？

你本地测试可以先在 go.mod 中加一行 `replace github.com/trzsz/ssh_config => ../ssh_config`，`../ssh_config` 就是你本地 ssh_config 的路径。

**Comment by hzhq1255** [comment]
> 然后 trzsz-ssh 也提个 PR ？
> 
> 你本地测试可以先在 go.mod 中加一行 `replace github.com/trzsz/ssh_config => ../ssh_config`，`../ssh_config` 就是你本地 ssh_config 的路径。

我本地测试过了，github.com/trzsz/ssh_config 版本还是填 v1.3.0 不用动吗？

**Comment by lonnywong** [comment]
有 `replace` 就不会管那个版本号的了。

**Comment by hzhq1255** [comment]
> 有 `replace` 就不会管那个版本号的了。
行 那trzsz-ssh 我直接提PR了，麻烦你看下，include 的hosts 我加在列表最后了，你看合不合适。

**Comment by lonnywong** [comment]
Include 的 Include 是不是也支持的？

因为 Include 是放在 config 的最前面，是不是 Include 的在前面，当前 config 的在后面，会更好一些？

**Comment by hzhq1255** [comment]
> Include 的 Include 是不是也支持的？
> 
> 因为 Include 是放在 config 的最前面，是不是 Include 的在前面，当前 config 的在后面，会更好一些？

include 可以支持 include 的，但是目前我的实现不行需要改成递归
include的节点我移到 config 前面好了，这样符合习惯一点，晚上我再改一版。

**Comment by lonnywong** [comment]
https://github.com/trzsz/ssh_config 我打了个新 tag `v1.3.1` ，你可以把 go.mod 中的 `replace` 去掉了，更新一下：
```
go get -u ./...
go mod tidy
```

**Comment by hzhq1255** [comment]
> https://github.com/trzsz/ssh_config 我打了个新 tag `v1.3.1` ，你可以把 go.mod 中的 `replace` 去掉了，更新一下：
> 
> ```
> go get -u ./...
> go mod tidy
> ```

已经更新递归方式获取hosts的函数了，本地大致测了下没啥问题。

**Comment by lonnywong** [comment]
@hzhq1255 感谢提的 PR 🎉
