### ISSUE TITLE
FR:  希望支持命令行参数(主机名)模糊匹配

### ISSUE THREAD

**Issue by boomker** [trzsz/trzsz-ssh#37]
<img width="679" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/ff197e3b-9d7b-49ca-98c5-5156a5105e3e">
上图所示， 希望`tssh`支持终端 命令行第一个参数(主机名)可以被模糊匹配到，目前只能输入完整的主机别名才会被匹配到

**Comment by lonnywong** [comment]
这个不是很好区分，你现在输入的 `storage` 是想匹配，另外一个用户可能是想直接登录，例如在 `/etc/hosts` 中有一条 `storage` 的域名配置，就可以解释域名登录的了。

现在 `v0.1.9` 不带参数运行 `tssh`，然后按  `/` ，再输入 `storage`，然后按两次回车，就登录了。比你在命令行输入，多按了一次 `/` 和一次回车键。

**Comment by boomker** [comment]
或者我换一种表达:
当用户 命令行 主机名参数(kw_host) 无法完整匹配一个主机的时候， `tssh` 自动将`kw_host`填充到搜索框过滤主机列表

**Comment by lonnywong** [comment]
这应该可以，但首先要能明确区分这不是 IP 或域名，/etc/hosts 中可以有很简单的域名的。可能要尝试解释一下，并且不能在解释时因网络问题卡住了，要好好研究一下怎么搞。

**Comment by lonnywong** [comment]
已实现，在下个版本发布之前，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样先安装试用。

**Comment by boomker** [comment]
> 已实现，在下个版本发布之前，可以 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` 这样先安装试用。

---
棒棒哒，👍
