### ISSUE TITLE
Windows Terminal登录成功后能否变更一下标签标题？

### ISSUE THREAD

**Issue by mx4994** [trzsz/trzsz-ssh#38]
![image](https://github.com/trzsz/trzsz-ssh/assets/52325833/be9d1f61-378d-4cd4-84ac-e048a42233ef)
如图，现在是原来的标题，多开几个之后，在一样用户名的情况下，容易搞混那个是那台机子了，能不能把配置里面的名字登录后变更为标签标题呢？

**Comment by lonnywong** [comment]
更好的办法是在每台服务器的 `~/.bashrc` 或 `~/.bash_profile` 等文件中加一两行：
```sh
mytitle=XXX
export PROMPT_COMMAND="echo -ne \"\\033]0;$mytitle\\007\""
```
其中 `mytitle` 你可以根据自己想要的进行修改。

这样做的好处是，当你从服务器上再 ssh 到另外一台服务器，另外一台服务器也设置了，那就会显示另外一台机器的，退出后又会自动切换回来。

**Comment by lonnywong** [comment]
这个不属于 ssh 的功能哈，一般的终端都会支持这个的。

**Comment by lonnywong** [comment]
@mx4994 我中午在微信收到一笔打赏，是不是你支付的？

**Comment by lonnywong** [comment]
> 终端支持，人不知道设置方法，还是白瞎。😂
> 
> 哈哈哈，挺好用的这个，请你喝杯奶茶。

感谢打赏 🍺

**Comment by lonnywong** [comment]
在 `~/.tssh.conf` 中配置 `SetTerminalTitle = Yes`，就支持自动修改标题了，可参考 [个性配置](https://github.com/trzsz/trzsz-ssh/blob/main/README.cn.md#%E4%B8%AA%E6%80%A7%E9%85%8D%E7%BD%AE)。

**Comment by evernethq** [comment]
我按照这个方法设置了，刚登录进去的时候我看到标题变为我设置的，但是很快就会变回${USER}@${HOSTNAME}。我的 windows terminal 版本为 1.22.10731.0

**Comment by lonnywong** [comment]
> 我按照这个方法设置了，刚登录进去的时候我看到标题变为我设置的，但是很快就会变回${USER}@${HOSTNAME}。我的 windows terminal 版本为 1.22.10731.0

可以参考 https://github.com/trzsz/trzsz-ssh/issues/38#issuecomment-2782075434 试试
