### ISSUE TITLE
mac m1 执行 go install 报错

### ISSUE THREAD

**Issue by yiqiniu** [trzsz/trzsz-ssh#4]
github.com/trzsz/trzsz-go/trzsz
go/pkg/mod/github.com/trzsz/trzsz-go@v1.1.1/trzsz/pipeline.go:44:17: undefined: context.CancelCauseFunc
go/pkg/mod/github.com/trzsz/trzsz-go@v1.1.1/trzsz/pipeline.go:450:23: undefined: context.WithCancelCause
go/pkg/mod/github.com/trzsz/trzsz-go@v1.1.1/trzsz/pipeline.go:477:23: undefined: context.Cause
go/pkg/mod/github.com/trzsz/trzsz-go@v1.1.1/trzsz/pipeline.go:742:23: undefined: context.WithCancelCause
go/pkg/mod/github.com/trzsz/trzsz-go@v1.1.1/trzsz/pipeline.go:771:23: undefined: context.Cause
note: module requires Go 1.20

**Comment by lonnywong** [comment]
升级 go 到 1.20

brew update
brew upgrade
