### ISSUE TITLE
可否支持ControlPersist配置

### ISSUE THREAD

**Issue by jue-jue-zi** [trzsz/trzsz-ssh#43]
是否可以支持以下ssh配置，这样登陆跳板机可以只验证一次，后续的登陆会复用之前的链接

```
ControlMaster auto
ControlPath /tmp/%h_%p_%r
ControlPersist yes
```

**Comment by lonnywong** [comment]
参考 https://github.com/trzsz/trzsz-ssh/issues/29 ，有两个问题待解决：

1、go 的标准库有人提 PR 了 https://go-review.googlesource.com/c/crypto/+/383374 ，但是还没有合入。

2、即使上面说的 PR 合入了，还要求先用 openssh 登录一次，然后 go 实现的 ssh 客户端才能去复用那个连接。这需要 tssh 另外拉起一个 openssh 进程去登录，要让它能接受用户的输入，登录完后要让他后台运行，然后 tssh 再去复用它的连接。如果 go 的标准库也支持创建一个兼容  openssh 的连接就更好了。

以上，要等有空了，再仔细研究下，看有没有办法绕过，自己实现。

**Comment by lonnywong** [comment]
已支持 ControlMaster、ControlPath 和 ControlPersist。在 v0.1.13 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装后的路径在 ~/go/bin/tssh 。
