### ISSUE TITLE
bug ： 关于  .\.ssh\known_hosts 中有 空格的情况下，会使用不了

### ISSUE THREAD

**Issue by falseUtopia** [trzsz/trzsz-ssh#44]
在我的 known_hosts 中有一条记录

```
[demo.local]:2222,[fe80::20c:29ff:fe18:e2b5%以太网 6]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAfFFhkEb
```
这里出现了空格`以太网 6` 于是 tssh 连接时报错了

```
new knownhosts [C:\Users\xxx\.ssh\known_hosts] failed: knownhosts: C:\Users\xxx\.ssh\known_hosts:9: illegal base64 data at input byte 5
```

**Comment by lonnywong** [comment]
你把 `%以太网 6` 删了，变成 `[demo.local]:22,[fe80::20c:29ff:fe18:e2b5]:22` 这样，看能不能正常登录？看来是序列化 ipv6 地址时含有带中文的设备名称了，我研究一下看怎么避免。

**Comment by falseUtopia** [comment]
记录是tssh写的。
试了下，的确是空格导致，现修改 网络连接的名称 把空格去除后， 使用正常。
同时，在网络连接名称依然有空格的情况下，只把 `known_hosts` 中的空格删除掉，使用依然正常。
看看这个空格好不好处理。

**Comment by lonnywong** [comment]
端口不是 22 ，是 2222，对吧？那看着像是 tssh 写的。

有空格时，可以让 tssh 不写入 IP。这样，用 `tssh demo.local` 也是能正常登录的，不过用 `tssh "fe80::20c:29ff:fe18:e2b5%以太网 6"` 就还是会有问题。

**Comment by lonnywong** [comment]
@falseUtopia 有空帮测试一下以下两种能不能登录？可能会写往 known_hosts 写入有问题的记录，事后要自己清理一下。

```
tssh "fe80::20c:29ff:fe18:e2b5"

tssh "fe80::20c:29ff:fe18:e2b5%以太网 6"
```

**Comment by lonnywong** [comment]
@falseUtopia 最新的代码已经避免了往 known_hosts 中写入空格了，在 `0.1.12` 发布前，可以这样安装：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```

**Comment by falseUtopia** [comment]
> @falseUtopia 有空帮测试一下以下两种能不能登录？可能会写往 known_hosts 写入有问题的记录，事后要自己清理一下。
> 
> ```
> tssh -l username "fe80::20c:29ff:fe18:e2b5"
> 
> tssh -l username "fe80::20c:29ff:fe18:e2b5%以太网 6"
> ```

试了一把，两个都可以连

**Comment by lonnywong** [comment]
[tssh v0.1.12](https://github.com/trzsz/trzsz-ssh/releases) 已解决。
