### ISSUE TITLE
带#号密码无法正常工作

### ISSUE THREAD

**Issue by bequt** [trzsz/trzsz-ssh#45]
带#号密码无法正常工作
准确来说是末尾#号

**Comment by lonnywong** [comment]
`#` 被认为是注释了，密码加上双引号试试？如 `“abc123#”`

**Comment by bequt** [comment]
好的

**Comment by lonnywong** [comment]
@bequt @boomker 我计划再多加一个配置项 `EncPassword`，是一个简单的加密，密钥写在代码中（ 不是为了保密，但会起到防窥屏的作用，别人在屏幕上看到的是很长的密文，赌他一眼记不住 ）。运行 `tssh --enc-pass` 时，可以输入密码（ 不回显 ），然后会输出`密文`，配置 `EncPassword 密文` 即可，密文不会含有 `#` ，从而一并解决密码含有 `#` 的情况。

**Comment by boomker** [comment]
这个想法棒棒的，其实我还想更懒一点，密码可以帮我自动写入`~/.ssh/password`就更好了。

**Comment by lonnywong** [comment]
[tssh v0.1.12](https://github.com/trzsz/trzsz-ssh/releases) 支持配置加密，运行 `tssh --enc-secret`，输入密码，会输出一个`密文`，然后如下配置即可：
```
Host xxx
    encPassword 密文填在这
```
