### ISSUE TITLE
ssh 重连的方法

### ISSUE THREAD

**Issue by LazyMaple** [trzsz/trzsz-ssh#47]
打扰了，我的使用场景是这样：
tssh 可能会挂在后台运行，比如临时用ssh开一个隧道，这种时候需要一个稳定的后台服务，网络波动之类的情况可能导致ssh断掉，这个时候就需要重连，现在是用supervisor来写一个配置实现的。

请问下tssh可以通过配置或参数的方式来实现reconnect之类的效果么

**Comment by lonnywong** [comment]
你是用了 `-f` 后台运行？然后网络断开时，导致 tssh 进程退出了？

现在 tssh 拉起后台子进程后，父进程就退出了。

感觉可以加个参数，让父进程不退出，让它检测子进程是否存在，若子进程退出了，就重新拉起一个新的子进程。

**Comment by LazyMaple** [comment]
是的ssh 端口转发 -f -N 这种，调试的时候临时把端口弄出来。

**Comment by lonnywong** [comment]
@LazyMaple 是否只要在 tssh 进程退出后，自动拉起一个同样的进程，就可以满足需求？

**Comment by LazyMaple** [comment]
是的，如果这样就能满足了，操作起来就不用再用supervisor守护进程一类工具的再包一层了

**Comment by lonnywong** [comment]
OK，我周末抽空加个 `--reconnect` 参数。

**Comment by LazyMaple** [comment]
好的，感谢

**Comment by lonnywong** [comment]
[tssh v0.1.12](https://github.com/trzsz/trzsz-ssh/releases) 已支持 `--reconnect` 自动重连。
