### ISSUE TITLE
不等于和尖头的渲染问题

### ISSUE THREAD

**Issue by sober-wang** [trzsz/trzsz-ssh#48]
![image](https://github.com/trzsz/trzsz-ssh/assets/35804630/399128d3-a62b-449a-b2f3-fb42edf1c8dd)
请问这个两个符号是 tssh 渲染出来的吗？如果是如何还原成默认（!= , =>,->）的呢？

我使用 windows Terminal ，我应该如何设置让它显示为默认的。

**Comment by lonnywong** [comment]
你用 openssh 登录是怎么显示的？

**Comment by lonnywong** [comment]
一般是字体的问题，换个字体应该就好了。
