### ISSUE TITLE
tssh刚登录时拖拽上传文件失败

### ISSUE THREAD

**Issue by akronblim** [trzsz/trzsz-ssh#49]
使用tssh登录远程服务器，进去后直接拖拽文件，无法正常上传
![屏幕截图 2023-10-16 204145](https://github.com/trzsz/trzsz-ssh/assets/22946763/180d2102-7f86-40e9-a43e-3c39f32e9b64)

**Comment by lonnywong** [comment]
[tssh v0.1.12](https://github.com/trzsz/trzsz-ssh/releases) 已修复。
