### ISSUE TITLE
响应ctrl+space问题

### ISSUE THREAD

**Issue by finviman** [trzsz/trzsz-ssh#5]
v2ex过来的，今天刚装上，确实好用。有个小问题不知道能不能解决。
windows terminal，默认不能处理ctrl+space按键，比如我tmux prefix设置的这个就无效。查了下是openssh版本问题，windows10默认ssh版本8.1，如果升级到8.9以上，就能解决这个问题，前提是用ssh登录。
如果用tssh，即使ssh版本升级了仍然不行，我看另一issue说是用的go的一个ssh库，没用windows内置的，所以现在我判断是ssh库导致了ctrl+space无效，好像有点棘手了。
试了用其他terminal，比如windterm，执行tssh也有这个问题。

**Comment by lonnywong** [comment]
能找到 openssh 8.9 解决的 issue 或代码不？tssh 也应该是有办法解决的，要研究一下。

**Comment by FinallyFinancialFreedom** [comment]
https://github.com/microsoft/terminal/issues/4317这是原始issue，关联到https://github.com/microsoft/terminal/issues/2865这里，比较长，我没细看。下面有个人截图说8.9支持,我试了9.x都行。

**Comment by lonnywong** [comment]
@FinallyFinancialFreedom 感谢！

我看里面也有人提到了 ctrl + z ，我之前发现在 windows 中 ctrl + z 会变成 stdin 的 EOF 错误，在  [trzsz-go](https://github.com/trzsz/trzsz-go) 做了一下适配。

tssh 是依赖  [trzsz-go](https://github.com/trzsz/trzsz-go) 的，也间接解决了 ctrl + z 的问题。

ctrl + space 是个什么样的情况，我可能要到周末才有空深入研究下。

**Comment by lonnywong** [comment]
@FinallyFinancialFreedom tmux 默认的快捷键 ctrl + b 是好使的。

**Comment by FinallyFinancialFreedom** [comment]
> @FinallyFinancialFreedom tmux 默认的快捷键 ctrl + b 是好使的。

真不行，ubuntu可以，centos不行，可能我的问题，但没思路解决了。
我暂时不用tmux了，就terminal+tssh也解决了terminal不能rzsz的问题，够用。

**Comment by lonnywong** [comment]
https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.c
不知道有没有人有空将这个 c 代码用 go 重写出来，可以变成一个 go package，最好不用 cgo （除非能让用户方便地编译安装）。

在用 go 重写时，可以参考这个代码：
https://github.com/chzyer/readline/blob/master/rawreader_windows.go

**Comment by tanqiangyes** [comment]
有人做这个么？没有的话，我空闲的时候可以试试。（ps：最好能有设计文档帮助了解代码）

**Comment by lonnywong** [comment]
@tanqiangyes 暂时还没人反馈说在搞这个。

你要有兴趣搞的话，可以加 [README](https://github.com/trzsz/trzsz-ssh) 最下面的 QQ 群，然后加群主（ 我 ）的 QQ，聊一聊要怎么实现。

文档现在没有，主要就是抄 [tncon.c](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.c) 和 [tncon.h](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.h) 这两个文件的代码，用 Go 调 dll 实现。

**Comment by lonnywong** [comment]
@finviman  你可以参考 https://github.com/microsoft/terminal/pull/16298 ，加两行代码，然后自己用 Visual Studio 编译一个 Windows Terminal 来用。然后就支持 `Ctrl + Space` 了。
