### ISSUE TITLE
能否支持连接后执行一段 bash 脚本，比如自动进入服务器上某个目录

### ISSUE THREAD

**Issue by netcore-jroger** [trzsz/trzsz-ssh#52]
**如题：** 能否支持连接后执行一段 bash 脚本，比如自动进入服务器上某个目录

**Comment by lonnywong** [comment]
有三种办法：

1、你可以在 `~/.bash_profile` 或 `~/.bashrc` 中加些脚本，如 `cd /tmp`。

2、你可以在登录时，在后面加上命令，如 `tssh xxx 'cd /tmp; bash --login'`。

3、你可以在 `~/.ssh/config` 中配置：
```
Host test
    RemoteCommand cd /tmp; bash --login
```

**Comment by netcore-jroger** [comment]
方法 3 是我想要的功能，但是卡着一直登录不上。
![image](https://github.com/trzsz/trzsz-ssh/assets/3223890/8d8003d7-5b99-41e0-9d7b-9b7061ae2cee)

方法1、2都不是我想要的。

**Comment by lonnywong** [comment]
如果不配置 `RemoteCommand cd /tmp; bash --login` 就不会卡住？我本地测试是可以的，可能是你的环境不支持 `--login`，你试试把 `--login` 去掉？这样：
```
Host test
    RemoteCommand cd /tmp; bash
```

**Comment by netcore-jroger** [comment]
去掉 --login 还是不行。跟你配置的一样。还是卡着进不了系统。我的是CentOS 8

**Comment by lonnywong** [comment]
我感觉你应该是进入了，只是没有 shell 提示，你加个 `-t` 参数试试，`tssh -t xxx`。

**Comment by netcore-jroger** [comment]
CentOS Linux release 8.5.2111
用 `tssh -t` 可以。什么原因呀？

**Comment by lonnywong** [comment]
当 `RemoteCommand` 不为空时，默认是不启用 tty 的，`-t` 是启用 tty 。你可以下面这样配置，就不用加 `-t` 了：
```
Host test
    RemoteCommand cd /tmp; bash --login
    RequestTTY yes
```
