### ISSUE TITLE
服务器分组

### ISSUE THREAD

**Issue by fangzhengjin** [trzsz/trzsz-ssh#54]
有个想法, 能不能在 config 中通过一些配置对服务器进行分组, 然后展示的时候可以按分组展示? 手上服务器太多了, 好多名字和 IP 又是不同网络下的, 操作起来有点乱

**Comment by lonnywong** [comment]
现在是可以做到分组的，例如 `~/.ssh/config` 可以这样配置：

```
Host group1_host1
    HostName ...
Host group1_host2
    HostName ...

Host group2_host3
    HostName ...
Host group2_host4
    HostName ...

Host group2_index3_host5
    HostName ...
Host group2_index3_host6
    HostName ...
```

在你运行 `tssh` 之后，按 `/` 进入搜索模式，输入 `group2` 回车，就会只显示 `group2` 那组的机器了。

你还可以再次按 `/` ，再次进入搜雪纺衫模式，输入 `index3` 回车，就会只显示 `group2` 和 `index3` 两个标签的机器了。

另外，`Ctrl + E` 可以清空当前筛选的标签，回到初始状态。

**Comment by fangzhengjin** [comment]
好的好的  非常感谢

**Comment by lonnywong** [comment]
现在支持一种新的分组配置方式 `GroupLabels` 了。可以在 `ExConfigPath` 配置的文件（ 默认是 `~/.ssh/password` ）中配置，也可以直接在 `~/.ssh/config` 中配置（ 如果想兼容原来的 ssh ，则可以在配置前加上 `#!!` 前缀 ）。支持以空格分隔多个标签，支持多次配置 `GroupLabels`， 举例：
```
Host host1
    GroupLabels group1 index2
    #!! GroupLabels group3
    #!! GroupLabels group4 标签5 分组6
```

在 `v0.1.14` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装的路径在 `~/go/bin/` 。

**Comment by fangzhengjin** [comment]
666 点个赞(¯▽¯)👍



------------------ 原始邮件 ------------------
发件人: Lonny Wong ***@***.***&gt;
发送时间: 2023年11月25日 22:49
收件人: trzsz/trzsz-ssh ***@***.***&gt;
抄送: ZhengJin ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [trzsz/trzsz-ssh] 服务器分组 (Issue #54)





 
现在支持一种新的分组配置方式 GroupLabels 了。可以在 ExConfigPath 配置的文件（ 默认是 ~/.ssh/password ）中配置，也可以直接在 ~/.ssh/config 中配置（ 如果想兼容原来的 ssh ，则可以在配置前加上 #!! 前缀 ）。支持以空格分隔多个标签，支持多次配置 GroupLabels， 举例：
 Host host1     GroupLabels group1 index2     #!! GroupLabels group3     #!! GroupLabels group4 标签5 分组6  
在 v0.1.14 发布前，可以这样安装 go install ***@***.*** ，安装的路径在 ~/go/bin/ 。
