### ISSUE TITLE
建议将Host为空的内容过滤掉

### ISSUE THREAD

**Issue by fangzhengjin** [trzsz/trzsz-ssh#55]
建议将Host为空的内容过滤掉, 比如
<img width="404" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/12680972/22735973-57fe-4f44-9e96-a58b8d0f2b92">

配置内容如下
<img width="451" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/12680972/c6f4848d-f122-45d9-b4a2-c17ece083400">

**Comment by lonnywong** [comment]
如果你加了通配符，如 `Host test*`，是会过滤掉的。
