### ISSUE TITLE
能否设置主机列表时详情展示哪些字段？

### ISSUE THREAD

**Issue by coosir** [trzsz/trzsz-ssh#57]
<img width="486" alt="iShot_2023-11-26_17 35 31" src="https://github.com/trzsz/trzsz-ssh/assets/2175074/463a7037-e84f-4e91-b59e-d027de01cb7a">

tssh真的很好用，日常使用中有这个小问题：当有些主机 IdentityFile 或者 ProxyCommand 很长的时候，上下选择主机后会导致顶部的提示文字出现多行重复。

希望可以提供配置不展示这些字段，一方面是选择的时候不关心，另外也不会出现上述问题了。

**Comment by lonnywong** [comment]
如果超长时，省略掉中间的部分，是否也能满足诉求？

**Comment by coosir** [comment]
> 如果超长时，省略掉中间的部分，是否也能满足诉求？

是的~  或者其他办法能保证顶部提示文字不出现重复就好，移动时就不会突然有上下偏移的顿挫感

**Comment by coosir** [comment]
如果终端窗口足够高，貌似就有更多空间可以重复

<img width="468" alt="iShot_2023-11-26_18 19 28" src="https://github.com/trzsz/trzsz-ssh/assets/2175074/e80d125b-23d7-435a-848b-1ddab74b3204">

**Comment by lonnywong** [comment]
> 如果终端窗口足够高，貌似就有更多空间可以重复
> 
> <img alt="iShot_2023-11-26_18 19 28" width="468" src="https://private-user-images.githubusercontent.com/2175074/285643734-e80d125b-23d7-435a-848b-1ddab74b3204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTQ1ODIsIm5iZiI6MTcwMDk5NDI4MiwicGF0aCI6Ii8yMTc1MDc0LzI4NTY0MzczNC1lODBkMTI1Yi0yM2Q3LTQzNWEtODQ4Yi0xZGRhYjc0YjMyMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMTAyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMwMjljYWJlZDZjNzkxMTNiNTI0OTRhYmYzZGI1NDU2NmRlYTEwZTM4Y2E0MmI2MzgyMTExOGNmMzc2MjE5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.43C5XbVWXumobJmXGP9KC4LXp3dQq6e3382ffxMDPVk">

这个重复，应该是有超长的行导致的吧？只要没有超长的行，就不会出现？

**Comment by coosir** [comment]
> 这个重复，应该是有超长的行导致的吧？只要没有超长的行，就不会出现？

没有，最长的内容也就只是换了一行而已

**Comment by lonnywong** [comment]
那个组件是这样的，只要换了一行就会导致第一行没删掉，就是你看到的效果了。我研究一下看看有没有办法禁止自动换行。

**Comment by lonnywong** [comment]
已解决，超长也不会换行了。另外，也支持在 `~/.tssh.conf` 中自定义 `PromptDetailItems` 了，默认值如下：
```
PromptDetailItems = Alias Host Port User GroupLabels IdentityFile ProxyCommand ProxyJump RemoteCommand
```

在 `v0.1.15` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装的路径在 `~/go/bin/` 。
