### ISSUE TITLE
没有配置ssh的界面？

### ISSUE THREAD

**Issue by lizhuangs** [trzsz/trzsz-ssh#58]
需要手动去.ssh/config配置么？有点麻烦

**Comment by lizhuangs** [comment]
呃，没有界面，想试用看一下的想法就打住了。。命令行的都是极客选手

**Comment by lizhuangs** [comment]
实际使用过程中，会有几十个ssh。如果查看和修改配置文件会很头大的。没有列表来得直接，而且同一类型的列表也会分组存放的。等有界面了我会再来试用的~先关注一波。目前用的xshell和tabby.

**Comment by pengatgstdev** [comment]
> 现在没有，等周末有空了，可能会实现一下。 [#39 (comment)](https://github.com/trzsz/trzsz-ssh/issues/39#issuecomment-1662008323)

反对, 配置文件中可以成千上万个host配置,界面要一个个打开添加或修改; 而且有模糊搜索,没必要有界面列表; 如果非要加界面, 单做一个界面版的给他们用吧

**Comment by lonnywong** [comment]
> > 现在没有，等周末有空了，可能会实现一下。 [#39 (comment)](https://github.com/trzsz/trzsz-ssh/issues/39#issuecomment-1662008323)
> 
> 反对, 配置文件中可以成千上万个host配置,界面要一个个打开添加或修改; 而且有模糊搜索,没必要有界面列表; 如果非要加界面, 单做一个界面版的给他们用吧

肯定不会影响现有的功能的，做也只是个 cli。

**Comment by lizhuangs** [comment]
> > 现在没有，等周末有空了，可能会实现一下。 [#39 (comment)](https://github.com/trzsz/trzsz-ssh/issues/39#issuecomment-1662008323)
> 
> 反对, 配置文件中可以成千上万个host配置,界面要一个个打开添加或修改; 而且有模糊搜索,没必要有界面列表; 如果非要加界面, 单做一个界面版的给他们用吧

你的意思是界面就不能模糊搜索么。而且分组以后，大部人列表就可以看清所有的配置吧。界面和命令行本身并不冲突。

**Comment by lonnywong** [comment]
这里的“界面”可能有歧义，我可能做的是这种 `cli`：

![promptui](https://media.giphy.com/media/xUNda0Ngb5qsogLsBi/giphy.gif)

**Comment by pengatgstdev** [comment]
> 你的意思是界面就不能模糊搜索么。而且分组以后，大部人列表就可以看清所有的配置吧。界面和命令行本身并不冲突。

我的意思是连xshell那种界面都不需要;  config配置文件中的也能查看所有的配置呀

**Comment by Abeautifulsnow** [comment]
Terminal UI tool的话，[bubbletea](https://github.com/charmbracelet/bubbletea) 可能更好一些。

> 这里的“界面”可能有歧义，我可能做的是这种 `cli`：
> 
> ![promptui](https://camo.githubusercontent.com/cb2f8d2976387f7eb629a7c561181d1870b39991f80c913cf15e37d2cb7c6a06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78554e6461304e67623571736f674c7342692f67697068792e676966) [ ![promptui](https://camo.githubusercontent.com/cb2f8d2976387f7eb629a7c561181d1870b39991f80c913cf15e37d2cb7c6a06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78554e6461304e67623571736f674c7342692f67697068792e676966) ](https://camo.githubusercontent.com/cb2f8d2976387f7eb629a7c561181d1870b39991f80c913cf15e37d2cb7c6a06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78554e6461304e67623571736f674c7342692f67697068792e676966) [ ](https://camo.githubusercontent.com/cb2f8d2976387f7eb629a7c561181d1870b39991f80c913cf15e37d2cb7c6a06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78554e6461304e67623571736f674c7342692f67697068792e676966)
> 
> Fork from https://github.com/manifoldco/promptui

Terminal UI tool的话，[bubbletea](https://github.com/charmbracelet/bubbletea) 可能更好一些。支持的功能更丰富一些。`promptui` 不太更新了都。

**Comment by lonnywong** [comment]
> Terminal UI tool的话，[bubbletea](https://github.com/charmbracelet/bubbletea) 可能更好一些。支持的功能更丰富一些。`promptui` 不太更新了都。

bubbletea 的 demo 我都看了，没找到我想要的。

promptui 是好久不更新了，我 fork 出来 [https://github.com/trzsz/promptui](https://github.com/trzsz/promptui)， 想要什么功能就自己魔改了。

**Comment by lonnywong** [comment]
已支持 `tssh --new-host` 在 TUI 界面轻松添加 SSH 配置，并且完成后可以立即登录。

在 `v0.1.15` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装的路径在 `~/go/bin/` 。

**Comment by lonnywong** [comment]
> Terminal UI tool的话，[bubbletea](https://github.com/charmbracelet/bubbletea) 可能更好一些。支持的功能更丰富一些。`promptui` 不太更新了都。

@Abeautifulsnow 我还是用 `bubbletea` 来实现了，比 `promptui` 稳定很多，不会偶尔出现界面混乱的现象。

**Comment by lonnywong** [comment]
> 另外有个疑问，如果后续这种自动方式的情况下，会有cli支持删除某个old的ssh或者change password的功能不？😂

还有很多优先级更高的想法，我会优先实现它们。

有兴趣可以参与来共建，在下面这个 switch 加个 case ，然后再用单独一个源文件实现一个工具：
https://github.com/trzsz/trzsz-ssh/blob/c1f14ff847f044e619cbf70ae118876e4001a744/tssh/tools.go#L293-L305
