### ISSUE TITLE
macos_x86_64 从 0.1.13 开始，不能自动输入密码

### ISSUE THREAD

**Issue by 4ft35t** [trzsz/trzsz-ssh#59]
0.1.12 可以正常输入
```
debug: the hex code for question 'Password: ' is 50617373776f72643a20
debug: open config [/Users/x/.ssh/password] success
debug: decode config [/Users/x/.ssh/password] success
debug: no extended config [enc50617373776f72643a20] for [xxx]
debug: get extended config [50617373776f72643a20] for [xxx] success
```
0.1.13 及 0.1.14，没有出现 Question 相关内容
```
debug: /Users/x/.tssh.conf does not exist
debug: open config [/Users/x/.ssh/config] success
debug: decode config [/Users/x/.ssh/config] success
debug: open config [/etc/ssh/ssh_config] success
debug: decode config [/etc/ssh/ssh_config] success
debug: open config [/Users/x/.ssh/password] success
debug: decode config [/Users/x/.ssh/password] success
debug: control master: /usr/bin/ssh -T -oRemoteCommand=none -oConnectTimeout=5 -v xxx echo ok; sleep 2147483; sleep infinity

ssh 的 debug 信息
```

**Comment by lonnywong** [comment]
新版本支持了 `ControlMaster` 这个特性，但是这个特性与`记住密码`是不兼容的。

你可以将 `ControlMaster` 设置为 `no`，或者直接删除或注释掉 `ControlMaster` 那个配置。

**Comment by 4ft35t** [comment]
我的 `ControlPersist` 是写在 `Host *` 下面的。 在具体的 Host 里设置 `ControlMaster no` 无法覆盖掉。

```conf
Host *
    TCPKeepAlive yes
    ServerAliveInterval 60
    ServerAliveCountMax 10

    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/master-%r@%h:%p
```

日常 ssh 使用依赖 `ControlMaster`，我还是继续用老版本好了。

**Comment by lonnywong** [comment]
@4ft35t ssh config 是按先后顺序匹配的，匹配到了就立即返回。
你可以将 `Host *` 放在具体 `Host xxx` 的后面，那样就是 `Host xxx` 的配置先生效了。

**Comment by 4ft35t** [comment]
> @4ft35t ssh config 是按先后顺序匹配的，匹配到了就立即返回。 你可以将 `Host *` 放在具体 `Host xxx` 的后面，那样就是 `Host xxx` 的配置先生效了。

放在 `Host *` 之前确认有效

**Comment by 4ft35t** [comment]
另外我发现，在有 ControlMaster 设置的情况下，提示输入密码时，按一下 `Ctrl+c`，就能进入密码自动填写流程。

**Comment by lonnywong** [comment]
> 另外我发现，在有 ControlMaster 设置的情况下，提示输入密码时，按一下 `Ctrl+c`，就能进入密码自动填写流程。

是这样的，有 `ControlMaster` 时，tssh 会调起原生的 ssh 子进程，是 ssh 子进程让你输入密码的，如果你及时中断了 ssh 子进程，那 tssh 进程就会发现 `ControlMaster` 连不通，然后尝试自己直接登录，就会有`记住密码` 的功能了。会有 warning 输出。

**Comment by lonnywong** [comment]
计划用类似 `expect` 的方式，支持开启了 `ControlMaster` 时的记住密码功能：https://github.com/trzsz/trzsz-ssh/issues/64#issuecomment-1853170951
