### ISSUE TITLE
能否支持expect，方便跳板机环境下使用

### ISSUE THREAD

**Issue by gosk8** [trzsz/trzsz-ssh#6]
eg.:

expect "Select Server:" {send "0"}
expect "Select User:" {send "admin\r"}

**Comment by lonnywong** [comment]
应该不用改就可以直接支持的吧？

现在用 tssh 代替 ssh 之后，与 expect 结合使用时，有报什么错，或者表现与 ssh 时有什么不同？

**Comment by lonnywong** [comment]
@gosk8 多给一点信息？现在是在哪个点出了问题？

**Comment by gosk8** [comment]
> @gosk8 多给一点信息？现在是在哪个点出了问题？

我昨晚尝试了一下，应该完美支持的，最开始我以为expect是ssh的功能，是我弄错啦
感谢大佬的工具，很方便

**Comment by lonnywong** [comment]
现在 tssh 内置支持简单的 expect 功能了，用法参考 [README](https://github.com/trzsz/trzsz-ssh#%E8%87%AA%E5%8A%A8%E4%BA%A4%E4%BA%92)。

在 `v0.1.16` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装的路径在 `~/go/bin/` 。
