### ISSUE TITLE
iTerm2中使用批量登录失败，需另外开启一个选项才能成功

### ISSUE THREAD

**Issue by huaweiouba** [trzsz/trzsz-ssh#60]
如题，不仅要开启 Python API，还需要在Preferences... / Settings... -> Advanced，筛选 COOKIE，选择 Yes。否则无法使用批量登录功能。

因不清楚iTerm2的机制，不确定是代码缺陷还是文档缺陷，故提一个issue

**Comment by lonnywong** [comment]
感谢反馈，这是个 tssh 的 bug，我修复一下。

**Comment by lonnywong** [comment]
@huaweiouba 已修复
