### ISSUE TITLE
jar类型文件trz上传速度

### ISSUE THREAD

**Issue by zhouJianXXX** [trzsz/trzsz-ssh#61]
![66975a8e24a481096b5d5d79f1938494](https://github.com/trzsz/trzsz-ssh/assets/148297829/fc0dc201-b335-4d6e-a743-dee8e1bba369)
![14d17d85762aef2a3482b5d02f77ed87](https://github.com/trzsz/trzsz-ssh/assets/148297829/f2d5c762-c62c-4b6f-869e-7fa7f5d7e7ff)

上传200多的log文件测试正常，但是jar包文件就极其慢。。。

**Comment by lonnywong** [comment]
log  快是因为 log 文件的压缩率高，显示的速度不是网络本身的速度。根本问题还是网络慢，或者跳板机慢。
