### ISSUE TITLE
希望能够在登录success后仍有简单的expect可以执行

### ISSUE THREAD

**Issue by zhouJianXXX** [trzsz/trzsz-ssh#62]
登录跳板机后仍有其他交互需要输入，能够增加此新特性吗？

**Comment by lonnywong** [comment]
已支持，用法参数 [README](https://github.com/trzsz/trzsz-ssh#%E8%87%AA%E5%8A%A8%E4%BA%A4%E4%BA%92)。

在 `v0.1.16` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，安装的路径在 `~/go/bin/` 。
