### ISSUE TITLE
ssh xx 记住密码之后仍提示需要输入密码

### ISSUE THREAD

**Issue by zlsq** [trzsz/trzsz-ssh#64]
环境：macos  + warp终端 + 已经使用软连接 sudo ln -sv $(which tssh) /usr/local/bin/ssh
问题： 通过ssh --new-host配置成功之后，能成功通过 tssh xx、 ssh 选择 xx登陆。但是直接 ssh xx 会提示让输入密码，我直接control + c 退出又可以ssh登陆成功，显示信息如下：

```shell
ssh xx
root@10.9.2.68's password:
Warning: start control master failed: interrupt
Warning: dial ctrl unix [/Users/shuqin/.ssh/170243192817852] failed: dial unix /Users/shuqin/.ssh/170243192817852: connect: no such file or directory
```

**Comment by lonnywong** [comment]
因为 `Warp` 会开启 `ControlMaster` 的功能，它那个分块的功能依赖这个。

`tssh` 是用 `go` 实现的，现在 `go` 的库还不支持 `ControlMaster` 相关的功能，于是 `tssh` 就本地调起了一个 `ssh` 进程来做 `ControlMaster` 的事。要求输入密码是 `ssh` 进程的行为，所以 `tssh` 记住密码的功能看起来就不生效了。

我计划像 [自动交互](https://github.com/trzsz/trzsz-ssh#%E8%87%AA%E5%8A%A8%E4%BA%A4%E4%BA%92) 那样，用类似 `expect` 的方式，支持 `Warp` 这种启用了 `ControlMaster` 时的“记住密码”的功能。

到时，大概会这样配置：
```
Host xxx
    #!! CtrlExpectCount 1  # 一般只要一次交互
    #!! CtrlExpectSendPass1 de88c4dbdc95d85303682734e2397c4d8dd29bfff09ec53580f31dd40291fc8c7755  # 用 tssh --enc-secret 得到的密码的密文串 
```

**Comment by lonnywong** [comment]
已实现，详见 [README](https://github.com/trzsz/trzsz-ssh#%E8%AE%B0%E4%BD%8F%E5%AF%86%E7%A0%81)。

在 `v0.1.16` 发布前，可以这样安装：
```sh
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
sudo rm /usr/local/bin/ssh
sudo ln -sv ~/go/bin/tssh /usr/local/bin/ssh
```
