### ISSUE TITLE
希望连接之后，修改标题名称为ip地址

### ISSUE THREAD

**Issue by scstc** [trzsz/trzsz-ssh#65]
![image](https://github.com/trzsz/trzsz-ssh/assets/17975927/09bde27b-b0af-4aa4-ac1e-e788e90e66e9)

**Comment by lonnywong** [comment]
建议用这种方式：https://github.com/trzsz/trzsz-ssh/issues/38#issuecomment-1661396833

**Comment by lonnywong** [comment]
已在 [README](https://github.com/trzsz/trzsz-ssh#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) 中添加相应的说明。

**Comment by lonnywong** [comment]
@scstc `v0.1.16` 在 `~/.tssh.conf` 中配置 `SetTerminalTitle = Yes`，就支持自动修改标题了。
强烈建议仔细阅读 [README](https://github.com/trzsz/trzsz-ssh?tab=readme-ov-file#%E5%85%B6%E4%BB%96%E5%8A%9F%E8%83%BD) 中关于 `PROMPT_COMMAND` 相关的说明。
