### ISSUE TITLE
是否有可能支持alacritty?

### ISSUE THREAD

**Issue by BrightXiaoHan** [trzsz/trzsz-ssh#66]
https://github.com/alacritty/alacritty

**Comment by lonnywong** [comment]
我在 MacOS 和 Windows 都安装试了一下，是支持的呀，没发现有什么问题。

只要是支持本地 shell 的终端，`tssh` 都支持。

**Comment by BrightXiaoHan** [comment]
sorry，我上次尝试trz，文件管理器没弹出来，刚才尝试能够正常弹出。
