### ISSUE TITLE
登录服务器后，退出会有乱码

### ISSUE THREAD

**Issue by arlequinfei** [trzsz/trzsz-ssh#67]
在windows powershell下，登录linux服务器后，使用exit退出登录，会有乱码

![pp20231224125730](https://github.com/trzsz/trzsz-ssh/assets/58545937/4bf9567a-bf5d-444b-8014-7a38b253d008)

**Comment by lonnywong** [comment]
`tssh -V` 看看是哪个版本？你的 Windows 是不是 PD 虚拟机？

**Comment by arlequinfei** [comment]
版本是：0.1.16
![image](https://github.com/trzsz/trzsz-ssh/assets/58545937/ce038993-db9b-4a37-b2a7-6d7884c399e8)

**Comment by lonnywong** [comment]
旧版本 0.1.15 是不是没有这个问题？

**Comment by arlequinfei** [comment]
嗯，旧版没有

![image](https://github.com/trzsz/trzsz-ssh/assets/58545937/2d902b8d-e9f4-4aa2-ab0a-2261c686a054)

**Comment by lonnywong** [comment]
我研究下

**Comment by lonnywong** [comment]
已修复。

在 `v0.1.17` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main` ，  
安装的路径在 `C:\Users\xxx\go\bin\` 。

**Comment by arlequinfei** [comment]
👍
