### ISSUE TITLE
font not display right

### ISSUE THREAD

**Issue by KimBioInfoStudio** [trzsz/trzsz-ssh#68]
https://github.com/trzsz/trzsz-ssh/blob/main/tssh/prompt.go#L41C25-L41C27
could we use a config to set those two font?

**Comment by lonnywong** [comment]
What is your environment? And what fonts do you use? Did you compile it yourself?

**Comment by KimBioInfoStudio** [comment]
> What is your environment? And what fonts do you use? Did you compile it yourself?

iam using the bin downloaded from the github release page, and iam using a font [DejaVu Sans Mono for Powerline](https://github.com/powerline/fonts/tree/master/DejaVuSansMono) for my ssh tool [Tabby](https://tabby.sh) and code editor VSCode, and i think this two  icon font not include in my using font

**Comment by lonnywong** [comment]
OK, I'll make them configurable in `~/.tssh.conf`:
```
PromptCursorIcon = 🧨
PromptSelectedIcon = 🍺
```

Does the font support `✔` for multiple selection in `tmux`? https://github.com/trzsz/trzsz-ssh/blob/main/tssh/prompt.go#L565

**Comment by KimBioInfoStudio** [comment]
> OK, I'll make them configurable in `~/.tssh.conf`:
> 
> ```
> PromptCursorIcon = 🧨
> PromptSelectedIcon = 🍺
> ```
> 
> Does the font support `✔` for multiple selection in `tmux`? https://github.com/trzsz/trzsz-ssh/blob/main/tssh/prompt.go#L565
"✔ " is okay in my situation

**Comment by lonnywong** [comment]
Done in https://github.com/trzsz/trzsz-ssh/commit/9c936c6b3e8b04e5308a74571395569b8bfb79c0
