### ISSUE TITLE
it's hunged when transfer over jumpserver

### ISSUE THREAD

**Issue by omyhub** [trzsz/trzsz-ssh#71]
![image](https://github.com/trzsz/trzsz-ssh/assets/35255549/68f4a6ec-aa5a-48c5-be15-d35ae00bdf50)
经过堡垒机登录目标主机传输文件会卡住

**Comment by lonnywong** [comment]
你是不是用 `tssh` 登录堡垒机的？用 `tssh --debug` 登录看看，有没有输出 `EnableTrzsz` 相关的内容？

**Comment by lonnywong** [comment]
@omyhub 如果没有提供更多的信息，我就要关闭这 issue 了。当你提供了更多信息后，可以 reopen 。
