### ISSUE TITLE
服务端 trz 弹窗后无法选中文件

### ISSUE THREAD

**Issue by boomker** [trzsz/trzsz-ssh#72]
系统：
<img width="349" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/99942e43-09c1-4b90-a357-2f8c4c302588">

客户端软件版本：
❯ tssh --version
trzsz ssh 0.1.17

服务端软件版本：
[root@localhost ~]# trzsz --version
trzsz go 1.1.7

更新：
终端：  alacritty 0.13.1 (fe2a3c5)
tmux： tmux 3.3a

**Comment by lonnywong** [comment]
用的是什么终端？可能是你的终端没有权限打开上一次选择的目录。
1、你可以试试原生终端，或者其他终端。
2、如果其他终端可以，你先选择一个有权限的目录，然后估计就好了。
3、tssh 支持配置默认打开的目录的，详细你可以看看文档。

如果以上都不行，弹出的对话框可以截图看看？

**Comment by boomker** [comment]
> 用的是什么终端？可能是你的终端没有权限打开上一次选择的目录。 1、你可以试试原生终端，或者其他终端。 2、如果其他终端可以，你先选择一个有权限的目录，然后估计就好了。 3、tssh 支持配置默认打开的目录的，详细你可以看看文档。
> 
> 如果以上都不行，弹出的对话框可以截图看看？

___
终端用的是：  alacritty
通过测试， 其他终端 在本地不开 tmux 下可以上传文件， 本地 tmux 情况下无法上传文件

**Comment by boomker** [comment]
> > 通过测试， 其他终端 在本地不开 tmux 下可以上传文件， 本地 tmux 情况下无法上传文件
> 
> 不应该，是 tmux 之后，用 tssh 登录吗？

___
对的， 本地终端 alacritty 开 tmux， 然后再 tssh 登录。 发现 `tssh --dragfile --zmodem `， 可以拖文件上去，没法弹窗上传

**Comment by boomker** [comment]
补一个截图， 弹窗之后的窗口
<img width="1187" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/74bdbedc-5217-4bf6-b471-c7d00b40ebaf">

**Comment by lonnywong** [comment]
也有其他用户以为不支持  alacritty 终端 https://github.com/trzsz/trzsz-ssh/issues/66 ，实际是支持的，你升级 alacritty 看看。

**Comment by lonnywong** [comment]
> 对的， 本地终端 alacritty 开 tmux， 然后再 tssh 登录。 发现 `tssh --dragfile --zmodem `， 可以拖文件上去，没法弹窗上传

服务器上有安装 trzsz 吗，trz 在 PATH 路径中不？

**Comment by boomker** [comment]
> > 对的， 本地终端 alacritty 开 tmux， 然后再 tssh 登录。 发现 `tssh --dragfile --zmodem `， 可以拖文件上去，没法弹窗上传
> 
> 服务器上有安装 trzsz 吗，trz 在 PATH 路径中不？

---
服务器有安装的， 能弹出 Mac 本机窗口的， 但是在窗口里无法选中文件
alacritty 更新到最新版也是这样情况，问题依旧

**Comment by lonnywong** [comment]
> alacritty 更新到最新版也是这样情况，问题依旧

可能 Mac 曾经弹窗，问你是否允许 alacritty 访问 Downloads 目录，你拒绝了，然后就现在这样了。

你可以在 `~/.tssh.conf` 中配置 DefaultUploadPath 到非 Downloads 目录试试。或者找到 Mac 配置的地方，允许 alacritty 访问 Downloads 目录。

**Comment by boomker** [comment]
> > alacritty 更新到最新版也是这样情况，问题依旧
> 
> 可能 Mac 曾经弹窗，问你是否允许 alacritty 访问 Downloads 目录，你拒绝了，然后就现在这样了。
> 
> 你可以在 `~/.tssh.conf` 中配置 DefaultUploadPath 到非 Downloads 目录试试。或者找到 Mac 配置的地方，允许 alacritty 访问 Downloads 目录。

---
感觉是和 tmux 有关系， 在没开 tmux 的时候，在 alacritty 或其他终端都可以弹窗选中文件上传

**Comment by lonnywong** [comment]
> 感觉是和 tmux 有关系， 在没开 tmux 的时候，在 alacritty 或其他终端都可以弹窗选中文件上传
> 在配置文件里添加了，非 downloads 目录， 问题依旧

是和 tmux 有关，我大概知道是什么问题了，等我周末有空了研究一下怎么解决。

**Comment by lonnywong** [comment]
已解决。

在 `v0.1.18` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

**Comment by boomker** [comment]
close
