### ISSUE TITLE
 本地终端 tmux 批量开 window 无法同时登录多台远程设备

### ISSUE THREAD

**Issue by boomker** [trzsz/trzsz-ssh#73]
复现步骤；
1. 本地终端 tmux上执行 `tssh --dragfile --zmodem os_`
2. 在交互式选单里依次选中「os_」开头的服务器主机别名
3. 按下`Ctrl-t`，即可看到如下图，即不会自动登录所选中的服务器 

<img width="981" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/19751472/9db4388a-11cf-414c-998b-bfb43917d7ad">

**Comment by lonnywong** [comment]
感谢反馈，这是个问题，但不是很好处理，我抽空研究下怎么解决。

**Comment by lonnywong** [comment]
已解决。

在 `v0.1.18` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

**Comment by boomker** [comment]
close
