### ISSUE TITLE
【文件上传异常】上传第二个文件时，会出现异常

### ISSUE THREAD

**Issue by xingchen-FL** [trzsz/trzsz-ssh#76]
问题描述： trz 上传第二个文件时会闪退、Terminal 客户端无法进行任何操作

tssh版本： 0.1.17

tssh 直接连接服务器，无代理软件

Windows Terminal  版本: 1.18.3181.0

![image](https://github.com/trzsz/trzsz-ssh/assets/37186195/17c7364b-97b0-4679-9cce-f285a0d0d319)

**Comment by Pengfei-Qi** [comment]
补充：用的公钥登录方式

![image](https://github.com/trzsz/trzsz-ssh/assets/37186195/46c4767e-e2c8-48d8-9a04-ad038cdbb93b)

**Comment by lonnywong** [comment]
1. 用 `tssh --tracelog xxx` 登录。
2. trz 上传第一次文件
3. 执行 `echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'`，你会看到一个本地日志文件路径。
4. trz 上传第二次文件
5. 发第 3 步的日志文件到我的邮箱 lonnywong@qq.com

**Comment by lonnywong** [comment]
可能是 https://stackoverflow.com/questions/35366998/2nd-call-to-getopenfilename-crashes-without-error-on-win-8-1-64-bit-machine 这个问题

**Comment by lonnywong** [comment]
更新 [zenity](https://github.com/ncruces/zenity) 依赖后，已解决。

在 `v0.1.19` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
