### ISSUE TITLE
Additional Language

### ISSUE THREAD

**Issue by well-it-wasnt-me** [trzsz/trzsz-ssh#78]
Ever thought of having a lang file in order to translate this application ? is a very nice work !

**Comment by lonnywong** [comment]
It’s all written in English except `tssh --new-host`. What language do you want to translate it into?

I think `tssh --new-host` is not a commonly used tool. It is just a tool written for new users in Chinese. It is recommended that users edit the ssh config themselves.

**Comment by lonnywong** [comment]
Oh, if there is no `./.ssh/config` file, it will automatically switch to `tssh --new-host`. We can check the current system language and change it to English by default.

**Comment by lonnywong** [comment]
Or let the user choose a language manually on `tssh --new-host` startup.

**Comment by lonnywong** [comment]
done
