### ISSUE TITLE
提问: 技术上是否可以考虑用 sftp 替代 trz/tsz 做传输

### ISSUE THREAD

**Issue by Ehco1996** [trzsz/trzsz-ssh#80]
* 这个项目很有意思, 感谢开发者的付出

我不太了解背后的实现和技术背景,不过站在使用者的角度上看, 批量给服务器安装一个第三方组件还是挺麻烦的,所以才有了标题上的提问

**Comment by lonnywong** [comment]
首先，如果服务器有 rz / sz ，tssh 也是支持的。

如果是用 `tssh` 直接登录的，或者用 `ProxyJump` 跳过中间的服务器的，应该是可以用 sftp 或 scp 之类的来实现的：

- 前提：sftp 或 scp 本身是可行的（ trz / tsz 支持在 sftp 和 scp 玩不转的情况下还能用，如中间隔着跳板机等 ）。
- 上传：`echo` `我要上传文件啦`，tssh 监控到这个消息，就弹出对话框，让用户选择要上传的文件或目录，然后用 sftp 或 scp 来实现上传。
- 下载：`echo` `我要下载文件啦` `下载的文件`，tssh 监控到这个消息，就解释出 `下载的文件`，然后用 sftp 或 scp 来实现下载。

**Comment by sober-wang** [comment]
我的堡垒机通过 sftp 链接到堡垒机，看见的是一堆目录，需要 `cd <HOST_LINK_IDR>` ，才可以使用 Put 将本地文件放进目标主机。
sftp jumpserver -> cd <HOST_LINK_DIR> -> put D:\tmp\data.txt 
不知道这种方式是否能够实现。

**Comment by lonnywong** [comment]
最新的代码已支持 scp 和 sftp，参考 https://github.com/trzsz/trzsz-ssh/issues/199
