### ISSUE TITLE
ssh config 没有配置host的时候， 进入tssh 按一下右方向键再按一下上方向键会报错

### ISSUE THREAD

**Issue by bigruid** [trzsz/trzsz-ssh#85]
我的 ssh config 文件内容:

Host *
  ServerAliveInterval 30
  User root

tssh 报错内容
![image](https://github.com/trzsz/trzsz-ssh/assets/40227796/bb2e0bdb-f178-418d-8adb-a5c320e63417)

**Comment by lonnywong** [comment]
感谢反馈，已修复。

在 `v0.1.19` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
