### ISSUE TITLE
[功能请求] 增加指定IP协议版本的参数

### ISSUE THREAD

**Issue by devome** [trzsz/trzsz-ssh#86]
对标openssh，在命令行参数中增加指定IP协议版本的参数，如：

```shell
tssh -4
tssh --ipv4
tssh -6
tssh --ipv6
```

**Comment by lonnywong** [comment]
已支持 `-4`、`-6` 和 `AddressFamily` 配置。其中  `--ipv4` 和 `--ipv6` 是非标准的，暂不支持。

在 `v0.1.19` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。
