### ISSUE TITLE
win11【客户端】连接win11【服务端】失败

### ISSUE THREAD

**Issue by cffycls** [trzsz/trzsz-ssh#88]
使用ssh可以连接【ssh administrator@xx + 密码】；
tssh报错【debug】： failed: ssh: handshake failed: ssh: disconnect, reason 2: Too many authentication failures

服务端开启ssh配置参考：[《win10开启SSH服务通过内网穿透技术实现远程SSH访问》](https://blog.csdn.net/qq_36564503/article/details/124842114)

**Comment by lonnywong** [comment]
可以在配置中加个 `PubkeyAuthentication no` 来避免。
