### ISSUE TITLE
ssh自动补全

### ISSUE THREAD

**Issue by YiuTerran** [trzsz/trzsz-ssh#91]
直接使用ssh或者scp命令时，可以按tab自动补全匹配的host。用tssh代替ssh之后，这个功能就没有了，不太方便，希望能加回来。

**Comment by lonnywong** [comment]
你是安装了哪个软件来实现 ssh 自动补全的？可以试试将 tssh 改名为 ssh 来用。

**Comment by YiuTerran** [comment]
@lonnywong 是zsh自带的功能。我用了你的方案，把tssh改成ssh放在/usr/local/bin下，自动补全可以用了。

不过还是建议有个不那么trick的方案。

**Comment by lonnywong** [comment]
这个是 zsh 的实现逻辑，不是 ssh 的逻辑，tssh 也没法做。

**Comment by YiuTerran** [comment]
@lonnywong 可以参考这里：https://opensource.com/article/18/3/creating-bash-completion-script

**Comment by yingwenbo** [comment]
修改/usr/share/zsh/functions/Completion/Unix/_ssh
第一行：#compdef 添加tssh
ssh) 那一行修改为: tssh|ssh)

执行autoload -Uz compinit && compinit

然后就能和ssh一样的命令补全了
