### ISSUE TITLE
hash in ssh_config value cause truncate

### ISSUE THREAD

**Issue by warjiang** [trzsz/trzsz-ssh#92]
the ssh config  as follow:
```
Host wap1 # there is a proxy available for this one...
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
    Port 22
    User user_name
    IdentityFile path_to_private_key
    ProxyCommand ncat --proxy-type socks5 --proxy-auth 'user_name:pwd@#123_^&*' --proxy proxy_ip:proxy_port %h %p
```
value after '#' in line of ProxyCommand will be truncate. more detail can refer following links: 
https://github.com/trzsz/ssh_config/pull/2

**Comment by warjiang** [comment]
@lonnywong plz help

**Comment by lonnywong** [comment]
@warjiang Does openssh work properly?

**Comment by warjiang** [comment]
> @warjiang Does openssh work properly?

Yeah, it works

**Comment by lonnywong** [comment]
openssh supports `#` without `'` and `"`:
```
Host test
    LocalCommand echo Hello# World
    PermitLocalCommand yes
```

Need to study how openssh does it. But I've been busy recently.

**Comment by warjiang** [comment]
@lonnywong 

First i should admit that i have little knowledge of openssh, even bunch of knowledge came from daily usage 🤣 .

May be it's not right time to talk further, you can recheck this when you are free. Feel free to review it 😄 .
What i want to express is that, the `ssh_config` pkg cannot parse `#` char in side string literal.

The test code as follow:
```go
func main() {
	configData := `Host test
    LocalCommand echo Hello'#' World
    PermitLocalCommand yes`
	cfg, err := ssh_config.Decode(strings.NewReader(configData))
	if err != nil {
		panic(err)
	}
	v, err := cfg.Get("test", "LocalCommand")
	if err != nil {
		panic(err)
	}
	debug("value is %s", v)
}
```


before fixed:
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/7443b3b4-ce40-45e4-90ab-8aed049faa22)

after fixed:
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/f7a5fa04-5f44-4ed4-913e-ee1912b0030f)



Apart from that, i've tested in openssh client, i mock a ssh config file like following:
```
Host wap1
    LocalCommand echo Hello# World 'test' "test"
    PermitLocalCommand yes
```
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/77f07aab-540d-4b85-bb12-fbd296c515da)

it's equla to command `echo Hello'#' World` no `echo Hello'`

**Comment by lonnywong** [comment]
@warjiang How about we make some changes like this:
```
Host comment
    Key1 = Value1 # This is part of the value, not a comment
    Key2   Value2 # This is a comment, not part of the value
```
The value of `Key1` is `Value1 # This is part of the value, not a comment`. And the value of `Key2` is `Value2`.

**Comment by warjiang** [comment]
> @warjiang How about we make some changes like this:
> 
> ```
> Host comment
>     Key1 = Value1 # This is part of the value, not a comment
>     Key2   Value2 # This is a comment, not part of the value
> ```
> 
> The value of `Key1` is `Value1 # This is part of the value, not a comment`. And the value of `Key2` is `Value2`.

we should distinguish scene of `#`
- `#` in side single quote or doule quote
   in this case, `#` should be treated as a common literal
- `#` not   in side single quote or doule quote
   in this case, `#` should be treated as grammar of comment

so @lonnywong  should change code as following, if you want `#` as part of value
```
Host comment
    Key1 = 'Value1 # This is part of the value, not a comment'
    Key2   Value2 # This is a comment, not part of the value
```

**Comment by lonnywong** [comment]
It's not clear whether the value `'Value1 # This is part of the value, not a comment'` contains single quotes or not.

I think `=` means there is no comment at the end, which is simple and easy to distinguish. It's not exactly the same as openssh, but it's worth it.

**Comment by warjiang** [comment]
i've made serval test-case it in my local enviroment
```
Host wap
    LocalCommand = echo Value1 # This is part of the value, not a comment
    PermitLocalCommand yes
```
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/d0851c7e-a62a-49a3-84f1-3868b38b5482)

```
Host wap
    LocalCommand echo Value1 # This is part of the value, not a comment
    PermitLocalCommand yes
```
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/99a15263-a4d6-4d0d-9fb4-44699bc1533c)

> Conculsion: whether use equal sign, it turns out the same effect.

if wrap `#` with single quote as follow:
```
Host wap
    LocalCommand echo 'Value1 # This is part of the value, not a comment'
    PermitLocalCommand yes
```
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/26381fab-5f44-4013-8eb5-1cf2c47c0d6e)

**Comment by lonnywong** [comment]
I mean we change the code to do that.

**Comment by warjiang** [comment]
> It's not clear whether the value `'Value1 # This is part of the value, not a comment'` contains single quotes or not.
> 
> I think `=` means there is no comment at the end, which is simple and easy to distinguish. It's not exactly the same as openssh, but it's worth it.

maybe you are right, but it will casued some extra knowledge of another version of ssh config (like config of tssh) 😆 .

**Comment by warjiang** [comment]
> I mean we change the code to do that.

i can try it, but maybe we can use option to let user to choose whehter enable this feature.

**Comment by warjiang** [comment]
how about another im tools like wechat or tg? may be we can talk it for further.  the work under trzsz is very useful for me,  maybe i can take part in these project in deep. 🤔

**Comment by lonnywong** [comment]
> i can try it, but maybe we can use option to let user to choose whehter enable this feature.

I think most people will not use `=` in ssh config, even fewer use `=` and add comments at the end of the line.

We just need to document the new features of `=` in the new version.

> how about another im tools like wechat or tg? may be we can talk it for further. the work under trzsz is very useful for me, maybe i can take part in these project in deep. 🤔

There's a QQ group at the bottom of [README](https://github.com/trzsz/trzsz-ssh).

**Comment by warjiang** [comment]
> I think most people will not use `=` in ssh config, even fewer use `=` and add comments at the end of the line.
> 
> We just need to document the new features of `=` in the new version.

that's true~ i'll try it later 🔧

**Comment by warjiang** [comment]
I've implemented this feature by add `lexRReservedvalue` state. After detect equal, it will go to state of checking `lexRReservedvalue`.
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/6734f92c-aa66-4f3e-9066-2c9ac7bfcf32)

**Comment by warjiang** [comment]
> I've implemented this feature by add `lexRReservedvalue` state. After detect equal, it will go to state of checking `lexRReservedvalue`. ![image](https://private-user-images.githubusercontent.com/6478745/311558263-6734f92c-aa66-4f3e-9066-2c9ac7bfcf32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMTk1MTUsIm5iZiI6MTcxMDExOTIxNSwicGF0aCI6Ii82NDc4NzQ1LzMxMTU1ODI2My02NzM0ZjkyYy1hYTY2LTRmM2UtOTA2Ni0yYzlhYzdiZmNmMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDEwNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ0ODZkNWQ1ZDFlZTU0YTA5NThlNjIwM2NjMzQzYzBiYzRkZGRkNzZjZmY4MDllZjc1ZDlkMTYwNGEzOThkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UNe-_mxBkly4CveH_1Vkzb530OTPTQmvchwX0bGtyao)

for the ssh config as following:
```
Host comment
    Key1 = Value1 # This is part of the value, not a comment
    Key2   Value2 # This is a comment, not part of the value
```
the test case like following:
![image](https://github.com/trzsz/trzsz-ssh/assets/6478745/5b7eaa96-1660-4220-8c52-1dd4cd24c069)

**Comment by lonnywong** [comment]
I will write the documentation and update it this weekend.

**Comment by lonnywong** [comment]
done https://github.com/trzsz/trzsz-ssh/commit/a6c64a61aefa33c74d5ec7bdd6b211ec2713ce81
