### ISSUE TITLE
new conn [] failed: ssh: handshake failed

### ISSUE THREAD

**Issue by kzhui125** [trzsz/trzsz-ssh#93]
```
tssh  -p port root@server
new conn [server:port] failed: ssh: handshake failed: ssh: no common algorithm for host key; client offered: [ssh-rsa], server offered: [rsa-sha2-512 rsa-sha2-256]
```

mac, ssh 正常，tssh 报错，登录不上。

**Comment by lonnywong** [comment]
你的 `~/.ssh/config` 中有没有以下相关的配置，贴出来看看？
```
HostKeyAlgorithms
PubkeyAcceptedKeyTypes
ssh-rsa
rsa-sha2-512
rsa-sha2-256
```

**Comment by kzhui125** [comment]
```
Host xx
    HostName xx.net
    User root
    Port xxx
    ServerAliveInterval 30
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes
```

**Comment by kzhui125** [comment]
我的 `~/.ssh/config` 全是 Host 配置

**Comment by lonnywong** [comment]
在 `~/.ssh/known_hosts` 中找到对应的 IP 或 域名的行，临时删掉试试看？

**Comment by kzhui125** [comment]
删除之后，再登录（ssh 或者tssh会提示，选择yes可以登录），这一行记录的还是 `ssh-rsa`。
之后 tssh 还是不能登录，还是报错这个

**Comment by kzhui125** [comment]
本地测试了下，加了一行代码，没报错了

<img width="1254" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/11925432/96f918db-a763-452f-9092-a38a9d7ce4ad">

<img width="1194" alt="image" src="https://github.com/trzsz/trzsz-ssh/assets/11925432/b315981c-8c00-4798-8bb4-b24da0fb6d61">

**Comment by lonnywong** [comment]
你看前面 `HostKeyAlgorithms: kh.HostKeyAlgorithms(param.addr)`，
看来要优化一下这里的逻辑，当是 `ssh-rsa` 时，要把 `rsa-sha2-512` 和 `rsa-sha2-256` 加上。

**Comment by kzhui125** [comment]
确实 https://security.stackexchange.com/a/255087

**Comment by lonnywong** [comment]
更新 [knownhosts](https://github.com/skeema/knownhosts/pull/6) 依赖后，已解决。

在 `v0.1.19` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

**Comment by kzhui125** [comment]
👌
