### ISSUE TITLE
使用 lrzsz 报错 run rz client failed: exec: "rz": executable file not found in %PATH%

### ISSUE THREAD

**Issue by sober-wang** [trzsz/trzsz-ssh#95]
我的 `lrzsz` 安装配置
![image](https://github.com/trzsz/trzsz-ssh/assets/35804630/dd23bb93-30ed-40a8-97de-26f47653476d)

我使用 `windows Termninal`

**Comment by lonnywong** [comment]
是加到 Path 中，不是新建一个环境变量。

**Comment by lonnywong** [comment]
选中 Path ，编辑，添加 lrzsz 的路径，重启终端。
