### ISSUE TITLE
增加LoongArch架构支持

### ISSUE THREAD

**Issue by zoze0** [trzsz/trzsz-ssh#96]

**Comment by lonnywong** [comment]
你用对应的 go 1.20 以上编译，应该是能用的。
https://tip.golang.org/doc/go1.19
`GOOS=linux GOARCH=loong64 make`

**Comment by zoze0** [comment]
是可以的， 希望在release里能增加loongarch架构

**Comment by zoze0** [comment]
是可以的， 希望在release里能增加loongarch架构

**Comment by lonnywong** [comment]
> 是可以的， 希望在release里能增加loongarch架构

下个版本会自动增加 loong64 架构，在此之前可以这样验证下产物是否满足需求：

*要先安装 go 1.20 以上，以及要安装 [goreleaser](https://goreleaser.com/install/)，如下编译：*

```
git clone https://github.com/trzsz/trzsz-ssh.git
cd trzsz-ssh
goreleaser release --clean --snapshot --skip=publish
```

产物在 `disk` 目录下：
- tssh_0.1.19.next_linux_loong64.rpm
- tssh_0.1.19.next_linux_loong64.tar.gz

**Comment by zoze0** [comment]
验证无误
