### ISSUE TITLE
X11 Forwarding on Windows OS

### ISSUE THREAD

**Issue by ryanmi** [trzsz/trzsz-ssh#97]
我在Windows OS使用tssh代替ssh，来使用rz sz功能。
可不可以添加X11 Forwarding功能，目前还只能使用 ssh -Y

**Comment by lonnywong** [comment]
等我有空了研究一下。你可以先详细讲讲你在 Windows 是怎么用的，需要安装哪些软件，以及配置哪些东西等等。

**Comment by ryanmi** [comment]
Hi,

我是follow这个link配置的：https://in.nau.edu/arc/x11-forwarding-windows

- 基本就是安装Xming：winget install Xming.Xming
- 运行启动Xming
- 建立新的Environment Variables： DISPLAY
- 重新启动Windows Terminal，运行 ssh -Y user@linux-server，就可以启动图形界面程序了。

**Comment by lonnywong** [comment]
已支持。

在 `v0.1.20` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，Windows 安装的路径在 `C:\Users\xxx\go\bin\` 。
