### ISSUE TITLE
拖曳上传现在只支持trzsz, 能否支持lrzsz的拖曳上传？

### ISSUE THREAD

**Issue by bigruid** [trzsz/trzsz-ssh#98]
如题

**Comment by lonnywong** [comment]
技术上是可以做的，不过拖曳时 trz 与 rz 之间只能二选一，并且 rz 不支持拖目录。等我有空了再支持下。

**Comment by lonnywong** [comment]
已支持。

在 `v0.1.22` 发布前，可以这样安装 `go install github.com/trzsz/trzsz-ssh/cmd/tssh@main`，安装的路径在 `~/go/bin/` 。

拖曳使用 `rz` 上传可如下配置：
```
Host xxx
    #!! EnableZmodem yes
    #!! EnableDragFile yes
    #!! DragFileUploadCommand rz
```

`DragFileUploadCommand` 配置也支持加一些参数，如：
```
Host *
    #!! DragFileUploadCommand rz -yeb
```

又如，使用 `trz` 覆盖上传可如下配置：
```
Host *
    #!! DragFileUploadCommand trz -y
```
