### ISSUE TITLE
在 warp 中 block 功能不生效

### ISSUE THREAD

**Issue by fisherwei** [trzsz/trzsz-ssh#99]
warp v0.2024.03.19.08.01.stable_01
trzsz ssh 0.1.19
macos 14.3 (23D56)

按照文档 Trouble shooting 部分，执行了
`sudo ln -sv $(which tssh) /usr/local/bin/ssh`
并且验证了 `ssh -V` 是 tssh 而不是 ssh。

当执行 `ssh user@ip` 时，warp 的 block 是生效的。
但是，使用 `ssh` 进入 tssh 菜单，选择需要连接的主机后，block 不生效。

![image](https://github.com/trzsz/trzsz-ssh/assets/214470/0363208f-e483-42ca-b533-993fb3bd2ab9)

**Comment by lonnywong** [comment]
非直接登录，选择主机再登录，需要 Warp 支持才能实现，详见 https://github.com/warpdotdev/Warp/issues/3960 可以去点一下 👍 ，期待 Warp 可以提高优先级，支持一下。

**Comment by lonnywong** [comment]
我想到一个在 Warp 中兼容分块的办法：
1、修改一下源码，编译一个 tssh 出来，然后将编译出来的 tssh 复制到 `/usr/local/bin/ssh`（ 注意命名已变为 ssh ）。
```diff
@@ -156,7 +156,7 @@ func TsshMain() int {
        // choose ssh alias
        dest := ""
        quit := false
-       if args.Destination == "" {
+       if args.Destination == "" || args.Destination == "FAKE_DEST_IN_WARP" {
                if !isTerminal {
                        parser.WriteHelp(os.Stderr)
                        return 3
```

2、在 `.bash_profile` ( bash ) 或 `.zshrc` ( zsh ) 中添加以下 shell 函数定义：
```sh
tssh() {
    if [ $# -eq 0 ]; then
        ssh FAKE_DEST_IN_WARP
    else
        ssh "$@"
    fi
}
```
3、重新打开 Warp，使用 `tssh`（ 不带参数 ），将可以选择机器登录，并且支持分块功能。

**Comment by XIEJIAHAN** [comment]
@lonnywong 大佬，你好，我是在 mac 上用 `brew install trzsz-ssh` 安装的
但是tssh 安装的地址，好像不是你写的那个位置，你要删除的 ssh 命令也不在 `/usr/local/bin/ssh`
如果只是加 tssh 函数，会有问题；
请问还可以写详细点吗。。。。。感谢

**Comment by lonnywong** [comment]
> [@lonnywong](https://github.com/lonnywong) 大佬，你好，我是在 mac 上用 `brew install trzsz-ssh` 安装的 但是tssh 安装的地址，好像不是你写的那个位置，你要删除的 ssh 命令也不在 `/usr/local/bin/ssh` 如果只是加 tssh 函数，会有问题； 请问还可以写详细点吗。。。。。感谢

https://github.com/trzsz/trzsz-ssh/blob/main/README.cn.md#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4

**Comment by XIEJIAHAN** [comment]
> > [@lonnywong](https://github.com/lonnywong) 大佬，你好，我是在 mac 上用 `brew install trzsz-ssh` 安装的 但是tssh 安装的地址，好像不是你写的那个位置，你要删除的 ssh 命令也不在 `/usr/local/bin/ssh` 如果只是加 tssh 函数，会有问题； 请问还可以写详细点吗。。。。。感谢
> 
> https://github.com/trzsz/trzsz-ssh/blob/main/README.cn.md#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4
> 
> `sudo ln -sv $(which tssh) /usr/local/bin/ssh`

感谢大佬
